/**
 * Contract code generator.
 *
 * Single source of truth: the TypeBox schemas in `packages/contracts/src`.
 * Everything below is derived from them, so there is no hand-maintained
 * parallel enum set, Pydantic model or OpenAPI document anywhere in the repo
 * (00_AI_IMPLEMENTATION_INSTRUCTIONS.md, "Delivery discipline").
 *
 * Artifacts:
 *   packages/contracts/generated/schemas/<Name>.schema.json   JSON Schema 2020-12
 *   packages/contracts/generated/openapi.json                 OpenAPI 3.1
 *   services/worker/src/job_getter_worker/contracts/generated Pydantic v2 models
 *   packages/api-client/src/generated/client.ts               typed fetch client
 *
 * Usage:
 *   tsx scripts/generate.ts            write the artifacts
 *   tsx scripts/generate.ts --check    regenerate in memory and fail on drift
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, posix, relative, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { Kind, type TSchema } from '@sinclair/typebox';
import { EXPORTED_CONSTANTS, EXPORTED_ENUMS, EXPORTED_SCHEMAS } from '../src/exports.js';
import * as Contracts from '../src/index.js';
import { API_PREFIX, INTERNAL_PREFIX, ROUTES, type RouteDefinition } from '../src/routes.js';
import * as Protocol from '../src/tasks/protocol.js';

/* ------------------------------------------------------------------------- */
/* Paths                                                                      */
/* ------------------------------------------------------------------------- */

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const CONTRACTS_DIR = resolve(SCRIPT_DIR, '..');
const REPO_ROOT = resolve(CONTRACTS_DIR, '..', '..');

const SCHEMA_DIR = join(CONTRACTS_DIR, 'generated', 'schemas');
const OPENAPI_FILE = join(CONTRACTS_DIR, 'generated', 'openapi.json');
const PYTHON_DIR = join(
  REPO_ROOT,
  'services',
  'worker',
  'src',
  'job_getter_worker',
  'contracts',
  'generated',
);
const CLIENT_DIR = join(REPO_ROOT, 'packages', 'api-client', 'src', 'generated');
const CLIENT_FILE = join(CLIENT_DIR, 'client.ts');

/** Directories whose entire contents this generator owns. */
const MANAGED_DIRECTORIES = [SCHEMA_DIR, PYTHON_DIR, CLIENT_DIR];

const GENERATED_BY = 'packages/contracts/scripts/generate.ts';
const PY_HEADER = `# Generated by ${GENERATED_BY}. Do not edit by hand.`;
const TS_HEADER = `// Generated by ${GENERATED_BY}. Do not edit by hand.`;
const SCHEMA_ID_BASE = 'https://job-getter.local/schemas';

/* ------------------------------------------------------------------------- */
/* Generic JSON Schema helpers                                                */
/* ------------------------------------------------------------------------- */

type JsonValue = unknown;

interface JsonSchema {
  [key: string]: JsonValue;
}

type AnySchema = Record<string, JsonValue>;

/** Keys whose value is a single nested schema. */
const NESTED_SCHEMA_KEYS = ['items', 'not', 'propertyNames', 'contains', 'additionalProperties'];
/** Keys whose value is an array of nested schemas. */
const NESTED_SCHEMA_LISTS = ['anyOf', 'allOf', 'oneOf', 'prefixItems'];
/** Keys whose value is a record of nested schemas. */
const NESTED_SCHEMA_MAPS = ['properties', 'patternProperties', '$defs', 'definitions'];

function isPlainObject(value: unknown): value is AnySchema {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isSchemaObject(value: unknown): value is AnySchema {
  return isPlainObject(value);
}

function isTypeBoxSchema(value: unknown): value is TSchema {
  return isPlainObject(value) && Kind in value;
}

/** Own string keys with a defined value, in declaration order. */
function schemaKeys(node: AnySchema): string[] {
  return Object.keys(node).filter((key) => node[key] !== undefined);
}

function deepClone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function requiredSet(node: AnySchema): Set<string> {
  const required = node['required'];
  return new Set(Array.isArray(required) ? (required as string[]) : []);
}

function propertiesOf(node: AnySchema): AnySchema {
  const properties = node['properties'];
  return isPlainObject(properties) ? properties : {};
}

/* ------------------------------------------------------------------------- */
/* Naming helpers                                                             */
/* ------------------------------------------------------------------------- */

function pascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function camelCase(value: string): string {
  const pascal = pascalCase(value);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function screamingSnakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .toUpperCase();
}

/** Identity map: TypeBox schema object -> exported name. */
function buildIdentityMap(): {
  exportedSchemaName: Map<object, string>;
  anyExportName: Map<object, string>;
} {
  const exportedSchemaName = new Map<object, string>();
  for (const [name, schema] of Object.entries(EXPORTED_SCHEMAS)) {
    if (!exportedSchemaName.has(schema)) exportedSchemaName.set(schema, name);
  }
  const anyExportName = new Map<object, string>(exportedSchemaName);
  for (const [name, value] of Object.entries(Contracts)) {
    if (isTypeBoxSchema(value) && !anyExportName.has(value)) anyExportName.set(value, name);
  }
  return { exportedSchemaName, anyExportName };
}

const { exportedSchemaName, anyExportName } = buildIdentityMap();

/**
 * Structural fallback for the identity map. `Type.Optional(ContactValue)` clones
 * the schema, so identity alone would emit a duplicate model for a nested object
 * that is byte-for-byte an exported one. Canonical JSON keys close that hole.
 */
function canonicalKey(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalKey).join(',')}]`;
  if (isPlainObject(value)) {
    const keys = schemaKeys(value).sort();
    return `{${keys.map((key) => `${JSON.stringify(key)}:${canonicalKey(value[key])}`).join(',')}}`;
  }
  return JSON.stringify(value ?? null);
}

function buildStructureMap(source: Map<object, string>): Map<string, string> {
  const structure = new Map<string, string>();
  for (const [node, name] of source) {
    const key = canonicalKey(node);
    if (!structure.has(key)) structure.set(key, name);
  }
  return structure;
}

const exportedSchemaByStructure = buildStructureMap(exportedSchemaName);
const anyExportByStructure = buildStructureMap(anyExportName);

/** Exported name for a schema node, by object identity first and shape second. */
function lookupName(
  node: AnySchema,
  byIdentity: Map<object, string>,
  byStructure: Map<string, string>,
): string | undefined {
  return byIdentity.get(node) ?? byStructure.get(canonicalKey(node));
}

/**
 * TypeScript type names re-exported from `@job-getter/contracts`. The generated
 * client cannot resolve `@sinclair/typebox` itself, so it imports the aliases
 * that `src/**` already declares as `Static<typeof Schema>`.
 */
function collectExportedTypeNames(): Set<string> {
  const names = new Set<string>();
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
      a.name < b.name ? -1 : 1,
    )) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith('.ts')) {
        const source = readFileSync(full, 'utf8');
        for (const match of source.matchAll(/^export\s+(?:type|interface)\s+([A-Za-z0-9_]+)/gm)) {
          names.add(match[1] as string);
        }
      }
    }
  };
  walk(join(CONTRACTS_DIR, 'src'));
  return names;
}

const EXPORTED_TYPE_NAMES = collectExportedTypeNames();

/* ------------------------------------------------------------------------- */
/* (a) Standalone JSON Schema documents                                       */
/* ------------------------------------------------------------------------- */

export function buildJsonSchemaDocument(name: string, schema: TSchema): JsonSchema {
  const body = deepClone(schema) as AnySchema;
  delete body['$schema'];
  delete body['$id'];
  delete body['title'];
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: `${SCHEMA_ID_BASE}/${name}.schema.json`,
    title: name,
    ...body,
  };
}

/* ------------------------------------------------------------------------- */
/* (b) OpenAPI 3.1                                                            */
/* ------------------------------------------------------------------------- */

const ERROR_RESPONSES: ReadonlyArray<readonly [string, string]> = [
  ['400', 'Malformed request body, query or header.'],
  ['401', 'Unauthenticated: no valid session, device token or worker credential.'],
  ['403', 'Authenticated but not permitted for this workspace resource.'],
  ['404', 'Absent or not accessible from the authenticated workspace.'],
  [
    '409',
    'Conflict: stale revision, duplicate command or idempotency key reuse with a different body.',
  ],
  ['413', 'Payload exceeds the configured upload limit.'],
  ['422', 'Structurally valid but invalid domain input.'],
  ['429', 'Quota or rate limit exceeded.'],
];

interface OpenApiBuild {
  document: JsonSchema;
}

function openApiPath(prefix: string, path: string): string {
  return prefix + path.replace(/:([A-Za-z0-9_]+)/g, '{$1}');
}

function tagForPath(path: string): string {
  const segment = path.split('/').filter(Boolean)[0];
  return segment ? segment.replace(/[^A-Za-z0-9_-]/g, '') : 'root';
}

function securityFor(auth: RouteDefinition['auth']): JsonValue[] {
  switch (auth) {
    case 'public':
      return [];
    case 'session':
      return [{ sessionCookie: [] }];
    case 'device':
      return [{ deviceToken: [] }];
    case 'worker':
      return [{ workerToken: [] }];
    default:
      throw new Error(`Unhandled auth mode: ${String(auth)}`);
  }
}

/** Empty closed object: `{}` request bodies documented as such. */
function isEmptyClosedObject(schema: TSchema | undefined): boolean {
  if (!schema) return false;
  const node = schema as unknown as AnySchema;
  if (node['type'] !== 'object') return false;
  if (node['additionalProperties'] !== false) return false;
  return Object.keys(propertiesOf(node)).length === 0;
}

function isNullSchema(schema: TSchema | undefined): boolean {
  if (!schema) return false;
  return (schema as unknown as AnySchema)['type'] === 'null';
}

export function buildOpenApiDocument(): JsonSchema {
  const components = new Map<string, JsonSchema>();
  const inFlight = new Set<string>();

  const convert = (node: AnySchema): JsonSchema => {
    const name = lookupName(node, exportedSchemaName, exportedSchemaByStructure);
    if (name) {
      register(name, node);
      return { $ref: `#/components/schemas/${name}` };
    }
    return convertBody(node);
  };

  const convertBody = (node: AnySchema): JsonSchema => {
    const out: JsonSchema = {};
    for (const key of schemaKeys(node)) {
      const value = node[key];
      if (NESTED_SCHEMA_KEYS.includes(key) && isSchemaObject(value)) {
        out[key] = convert(value);
      } else if (NESTED_SCHEMA_LISTS.includes(key) && Array.isArray(value)) {
        out[key] = value.map((entry) =>
          isSchemaObject(entry) ? convert(entry) : deepClone(entry),
        );
      } else if (NESTED_SCHEMA_MAPS.includes(key) && isPlainObject(value)) {
        const mapped: JsonSchema = {};
        for (const child of schemaKeys(value)) {
          const childValue = value[child];
          mapped[child] = isSchemaObject(childValue) ? convert(childValue) : deepClone(childValue);
        }
        out[key] = mapped;
      } else {
        out[key] = deepClone(value);
      }
    }
    return out;
  };

  const register = (name: string, node: AnySchema): void => {
    if (components.has(name) || inFlight.has(name)) return;
    inFlight.add(name);
    const body = convertBody(node);
    inFlight.delete(name);
    components.set(name, body);
  };

  // Emit every exported schema so the document is a complete catalogue and
  // each one is referenced rather than duplicated.
  for (const [name, schema] of Object.entries(EXPORTED_SCHEMAS)) {
    register(name, schema as unknown as AnySchema);
  }

  const ref = (name: string): JsonSchema => ({ $ref: `#/components/schemas/${name}` });

  const errorResponses = (): JsonSchema => {
    const out: JsonSchema = {};
    for (const [status, description] of ERROR_RESPONSES) {
      out[status] = {
        description,
        content: { 'application/json': { schema: ref('ErrorEnvelope') } },
      };
    }
    return out;
  };

  const parametersFor = (route: RouteDefinition): JsonValue[] => {
    const parameters: JsonValue[] = [];
    if (route.params) {
      const node = route.params as unknown as AnySchema;
      const required = requiredSet(node);
      const properties = propertiesOf(node);
      for (const key of schemaKeys(properties)) {
        parameters.push({
          name: key,
          in: 'path',
          required: true,
          description: required.has(key) ? undefined : 'Path parameters are always required.',
          schema: convert(properties[key] as AnySchema),
        });
      }
    }
    if (route.query) {
      const node = route.query as unknown as AnySchema;
      const required = requiredSet(node);
      const properties = propertiesOf(node);
      for (const key of schemaKeys(properties)) {
        parameters.push({
          name: key,
          in: 'query',
          required: required.has(key),
          schema: convert(properties[key] as AnySchema),
        });
      }
    }
    if (route.requiresIdempotencyKey) {
      parameters.push({
        name: 'Idempotency-Key',
        in: 'header',
        required: true,
        description:
          'Mandatory for this command. Replaying the same key returns the stored response for 24 hours; reusing it with a different body returns 409.',
        schema: { type: 'string', minLength: 8, maxLength: 200 },
      });
    }
    if (route.csrf) {
      parameters.push({
        name: 'X-CSRF-Token',
        in: 'header',
        required: true,
        description: 'Anti-CSRF token for cookie-authenticated mutations; origin is verified too.',
        schema: { type: 'string', minLength: 8, maxLength: 200 },
      });
    }
    return parameters.map((parameter) => {
      const clean: JsonSchema = {};
      for (const [key, value] of Object.entries(parameter as AnySchema)) {
        if (value !== undefined) clean[key] = value;
      }
      return clean;
    });
  };

  const requestBodyFor = (route: RouteDefinition): JsonValue | undefined => {
    // A DELETE carries a body only when its route declares one; see
    // `deleteWorkspace` in src/routes.ts, whose password cannot go in a URL.
    const bodyless = route.method === 'GET' || (route.method === 'DELETE' && !route.body);
    if (!route.body || bodyless) return undefined;
    if (route.multipart) {
      return {
        required: true,
        description: 'multipart/form-data upload. Fields are form parts, not a JSON document.',
        content: {
          'multipart/form-data': {
            schema: convert(route.body as unknown as AnySchema),
          },
        },
      };
    }
    return {
      required: !isEmptyClosedObject(route.body),
      content: { 'application/json': { schema: convert(route.body as unknown as AnySchema) } },
    };
  };

  const successResponseFor = (route: RouteDefinition): JsonSchema => {
    if (route.successStatus === 204 || isNullSchema(route.response)) {
      return { description: `${route.summary} Returns no content.` };
    }
    if (route.binaryResponse) {
      return {
        description: `${route.summary} Streamed attachment.`,
        content: {
          'application/octet-stream': { schema: { type: 'string', format: 'binary' } },
        },
      };
    }
    return {
      description: route.summary,
      content: {
        'application/json': { schema: convert(route.response as unknown as AnySchema) },
      },
    };
  };

  const paths: JsonSchema = {};
  const addOperation = (path: string, method: string, operation: JsonValue): void => {
    const existing = isPlainObject(paths[path]) ? (paths[path] as JsonSchema) : {};
    const key = method.toLowerCase();
    if (existing[key] !== undefined) {
      throw new Error(`Duplicate operation ${method} ${path}`);
    }
    existing[key] = operation;
    paths[path] = existing;
  };

  for (const route of ROUTES) {
    const parameters = parametersFor(route);
    const requestBody = requestBodyFor(route);
    const operation: JsonSchema = {
      operationId: route.operationId,
      summary: route.summary,
      tags: [tagForPath(route.path)],
      security: securityFor(route.auth),
      responses: {
        [String(route.successStatus)]: successResponseFor(route),
        ...errorResponses(),
      },
    };
    if (parameters.length > 0) operation['parameters'] = parameters;
    if (requestBody !== undefined) operation['requestBody'] = requestBody;
    addOperation(openApiPath(API_PREFIX, route.path), route.method, operation);
  }

  /* Internal worker protocol (04_API_CONTRACTS.md, "Internal task protocol"). */
  const INTERNAL_NOTE =
    'Internal worker protocol. Not publicly routable: it is served on the internal listener only and authenticated with the operator worker credential, never a user device token.';

  interface InternalOperation {
    readonly operationId: string;
    readonly method: 'GET' | 'POST';
    readonly path: string;
    readonly summary: string;
    readonly pathParams?: readonly string[];
    readonly body?: TSchema;
    readonly multipart?: boolean;
    readonly successStatus: 200 | 201 | 204;
    readonly response?: TSchema;
    readonly binaryResponse?: boolean;
    readonly extraResponses?: Readonly<Record<string, string>>;
  }

  const INTERNAL_OPERATIONS: readonly InternalOperation[] = [
    {
      operationId: 'claimTask',
      method: 'POST',
      path: '/tasks/claim',
      summary: 'Claim the next eligible task for the declared capabilities.',
      body: Protocol.ClaimRequest,
      successStatus: 200,
      response: Protocol.ClaimResponse,
      extraResponses: { '204': 'No eligible task is currently queued.' },
    },
    {
      operationId: 'heartbeatTask',
      method: 'POST',
      path: '/tasks/{id}/heartbeat',
      summary: 'Extend the lease and report progress; learns about cancellation.',
      pathParams: ['id'],
      body: Protocol.HeartbeatRequest,
      successStatus: 200,
      response: Protocol.HeartbeatResponse,
    },
    {
      operationId: 'completeTask',
      method: 'POST',
      path: '/tasks/{id}/complete',
      summary: 'Submit a task result; the API validates it inside the completing transaction.',
      pathParams: ['id'],
      body: Protocol.CompleteRequest,
      successStatus: 200,
      response: Protocol.TaskAck,
    },
    {
      operationId: 'failTask',
      method: 'POST',
      path: '/tasks/{id}/fail',
      summary: 'Report a failure. The server, not the worker, decides whether a retry happens.',
      pathParams: ['id'],
      body: Protocol.FailRequest,
      successStatus: 200,
      response: Protocol.TaskAck,
    },
    {
      operationId: 'downloadTaskInputFile',
      method: 'GET',
      path: '/tasks/{id}/files/{file_id}',
      summary: 'Download a declared task input file under the active lease.',
      pathParams: ['id', 'file_id'],
      successStatus: 200,
      binaryResponse: true,
    },
    {
      operationId: 'uploadTaskArtifact',
      method: 'POST',
      path: '/tasks/{id}/artifacts',
      summary: 'Upload a scoped, staged output artifact for this task.',
      pathParams: ['id'],
      multipart: true,
      successStatus: 201,
      response: Protocol.ArtifactUploadResponse,
    },
  ];

  for (const operation of INTERNAL_OPERATIONS) {
    const parameters: JsonValue[] = (operation.pathParams ?? []).map((name) => ({
      name,
      in: 'path',
      required: true,
      schema: { type: 'string', format: 'uuid' },
    }));
    parameters.push({
      name: 'Authorization',
      in: 'header',
      required: true,
      description: 'Bearer <worker credential>. Lease ownership is checked per task as well.',
      schema: { type: 'string' },
    });

    const responses: JsonSchema = {};
    if (operation.binaryResponse) {
      responses[String(operation.successStatus)] = {
        description: `${operation.summary} Streamed attachment.`,
        content: { 'application/octet-stream': { schema: { type: 'string', format: 'binary' } } },
      };
    } else if (operation.response) {
      responses[String(operation.successStatus)] = {
        description: operation.summary,
        content: {
          'application/json': { schema: convert(operation.response as unknown as AnySchema) },
        },
      };
    } else {
      responses[String(operation.successStatus)] = { description: operation.summary };
    }
    for (const [status, description] of Object.entries(operation.extraResponses ?? {})) {
      responses[status] = { description };
    }
    for (const [status, description] of ERROR_RESPONSES) {
      responses[status] = {
        description,
        content: { 'application/json': { schema: ref('ErrorEnvelope') } },
      };
    }

    const built: JsonSchema = {
      operationId: operation.operationId,
      summary: operation.summary,
      description: INTERNAL_NOTE,
      tags: ['internal'],
      security: [{ workerToken: [] }],
      parameters,
      responses,
    };
    if (operation.multipart) {
      built['requestBody'] = {
        required: true,
        description: 'multipart/form-data artifact upload scoped to this task.',
        content: { 'multipart/form-data': { schema: { type: 'object' } } },
      };
    } else if (operation.body) {
      built['requestBody'] = {
        required: true,
        content: {
          'application/json': { schema: convert(operation.body as unknown as AnySchema) },
        },
      };
    }
    addOperation(INTERNAL_PREFIX + operation.path, operation.method, built);
  }

  const packageJson = JSON.parse(readFileSync(join(CONTRACTS_DIR, 'package.json'), 'utf8')) as {
    version?: string;
  };

  const sortedComponents: JsonSchema = {};
  for (const name of [...components.keys()].sort()) {
    sortedComponents[name] = components.get(name) as JsonSchema;
  }

  return {
    openapi: '3.1.0',
    info: {
      title: 'Job Getter API',
      version: packageJson.version ?? '0.0.0',
      description:
        `Generated from the TypeBox contracts in packages/contracts by ${GENERATED_BY}. ` +
        'Do not edit by hand. JSON snake_case, ISO-8601 UTC timestamps, UUID identifiers. ' +
        'The API derives the workspace from the authenticated principal and never trusts a client workspace_id.',
    },
    tags: [...new Set(ROUTES.map((route) => tagForPath(route.path)))]
      .sort()
      .map((name) => ({ name }))
      .concat([{ name: 'internal' }]),
    components: {
      securitySchemes: {
        sessionCookie: {
          type: 'apiKey',
          in: 'cookie',
          name: 'jg_session',
          description: 'HttpOnly session cookie issued by POST /auth/login.',
        },
        deviceToken: {
          type: 'http',
          scheme: 'bearer',
          description:
            'Scoped device token for the extension or local runner; expires after 30 days.',
        },
        workerToken: {
          type: 'http',
          scheme: 'bearer',
          description: 'Operator worker credential for the internal task protocol only.',
        },
      },
      schemas: sortedComponents,
    },
    paths,
  };
}

/* ------------------------------------------------------------------------- */
/* (c) Pydantic v2 models                                                     */
/* ------------------------------------------------------------------------- */

/**
 * `\d` and `\w` are Unicode-aware in both Rust's regex crate (which backs
 * Pydantic's `pattern`) and Python's `re`, but ASCII-only in the JavaScript
 * patterns these contracts are written against. Emitting explicit classes
 * keeps the two runtimes from disagreeing on, say, an Arabic-Indic digit.
 */
function toPythonPattern(jsPattern: string): string {
  let out = '';
  let inClass = false;
  for (let index = 0; index < jsPattern.length; index += 1) {
    const char = jsPattern[index] as string;
    if (char === '\\') {
      const next = jsPattern[index + 1];
      if (next === 'd' || next === 'w') {
        const body = next === 'd' ? '0-9' : 'A-Za-z0-9_';
        out += inClass ? body : `[${body}]`;
        index += 1;
        continue;
      }
      out += char + (next ?? '');
      index += 1;
      continue;
    }
    if (char === '[') inClass = true;
    else if (char === ']') inClass = false;
    out += char;
  }
  return out;
}

/** A Python raw string literal may not end with an odd run of backslashes. */
function trailingBackslashes(value: string): number {
  let count = 0;
  for (let index = value.length - 1; index >= 0 && value[index] === '\\'; index -= 1) count += 1;
  return count;
}

function splitRawChunks(value: string, budget: number): string[] {
  const chunks: string[] = [];
  let index = 0;
  while (index < value.length) {
    let end = Math.min(index + budget, value.length);
    while (end > index + 1 && trailingBackslashes(value.slice(index, end)) % 2 === 1) end -= 1;
    chunks.push(value.slice(index, end));
    index = end;
  }
  return chunks;
}

/**
 * Raw string literal. Splitting only ever happens between literals, which
 * Python concatenates implicitly, so the resulting pattern is byte-identical.
 */
function pyRawString(value: string): string {
  if (value.includes('"') || trailingBackslashes(value) % 2 === 1) {
    return JSON.stringify(value);
  }
  return `r"${value}"`;
}

function pyRawStringAssignment(name: string, value: string): string[] {
  const single = `${name} = ${pyRawString(value)}`;
  if (single.length <= PY_LINE_LENGTH) return [single];
  const chunks = splitRawChunks(value, PY_LINE_LENGTH - 10);
  return [`${name} = (`, ...chunks.map((chunk) => `    ${pyRawString(chunk)}`), ')'];
}

/**
 * The string formats these contracts use. `uuid` and `date-time` are mirrored
 * from `src/formats.ts` so the Python worker enforces exactly what
 * `Value.Check` enforces; `binary` is an OpenAPI transport hint with no
 * runtime meaning and is deliberately not validated.
 */
const PY_FORMAT_ALIASES: Readonly<Record<string, string>> = {
  uuid: 'UuidString',
  'date-time': 'TimestampString',
};
const PY_IGNORED_FORMATS = new Set(['binary']);

/** Read the authoritative format patterns out of `src/formats.ts`. */
function readFormatPatterns(): { uuid: string; dateTime: string } {
  const source = readFileSync(join(CONTRACTS_DIR, 'src', 'formats.ts'), 'utf8');
  const read = (constName: string): string => {
    const match = new RegExp(`const\\s+${constName}\\s*=\\s*/(.*)/([a-z]*);`).exec(source);
    if (match === null) {
      throw new Error(
        `generate.ts could not read ${constName} from src/formats.ts. The Python models mirror ` +
          'those regular expressions; update the extraction here if the file changed shape.',
      );
    }
    const pattern = toPythonPattern(match[1] as string);
    return (match[2] as string).includes('i') ? `(?i)${pattern}` : pattern;
  };
  return { uuid: read('UUID_PATTERN'), dateTime: read('DATE_TIME_PATTERN') };
}

/**
 * JSON Schema constraints that must survive into Pydantic. Dropping these is
 * not a cosmetic loss: the worker would then believe its own models are
 * authoritative and emit results that only fail at the API boundary.
 */
function pyFieldArguments(node: AnySchema): string[] {
  const args: string[] = [];
  const type = node['type'];
  const num = (key: string): number | undefined =>
    typeof node[key] === 'number' ? (node[key] as number) : undefined;

  if (type === 'string') {
    const minLength = num('minLength');
    const maxLength = num('maxLength');
    if (minLength !== undefined) args.push(`min_length=${minLength}`);
    if (maxLength !== undefined) args.push(`max_length=${maxLength}`);
    if (typeof node['pattern'] === 'string') {
      args.push(`pattern=${pyRawString(toPythonPattern(node['pattern'] as string))}`);
    }
  } else if (type === 'integer' || type === 'number') {
    const minimum = num('minimum');
    const maximum = num('maximum');
    const exclusiveMinimum = num('exclusiveMinimum');
    const exclusiveMaximum = num('exclusiveMaximum');
    const multipleOf = num('multipleOf');
    if (minimum !== undefined) args.push(`ge=${minimum}`);
    if (maximum !== undefined) args.push(`le=${maximum}`);
    if (exclusiveMinimum !== undefined) args.push(`gt=${exclusiveMinimum}`);
    if (exclusiveMaximum !== undefined) args.push(`lt=${exclusiveMaximum}`);
    if (multipleOf !== undefined) args.push(`multiple_of=${multipleOf}`);
  } else if (type === 'array') {
    const minItems = num('minItems');
    const maxItems = num('maxItems');
    if (minItems !== undefined) args.push(`min_length=${minItems}`);
    if (maxItems !== undefined) args.push(`max_length=${maxItems}`);
  }
  return args;
}

function annotate(expr: string, args: string[]): string {
  if (args.length === 0) return expr;
  return `Annotated[${expr}, Field(${args.join(', ')})]`;
}

interface PyField {
  readonly name: string;
  readonly type: string;
  readonly optional: boolean;
}

interface PyModel {
  readonly name: string;
  readonly fields: PyField[];
  readonly forbidExtra: boolean;
  readonly deps: Set<string>;
  readonly order: number;
}

interface PyTypeResult {
  readonly expr: string;
  readonly deps: ReadonlySet<string>;
  readonly imports: ReadonlySet<string>;
}

function pyLiteral(value: unknown): string {
  if (value === null) return 'None';
  if (value === true) return 'True';
  if (value === false) return 'False';
  if (typeof value === 'number') return String(value);
  return JSON.stringify(String(value));
}

interface PythonBuild {
  readonly models: string;
  readonly enums: string;
  readonly constants: string;
  readonly init: string;
  readonly modelNames: string[];
  readonly aliasNames: string[];
  readonly enumNames: string[];
  readonly constantNames: string[];
}

export function buildPython(): PythonBuild {
  const usedAliases = new Set<string>();
  const models = new Map<string, PyModel>();
  const nameByNode = new Map<object, string>(exportedSchemaName);
  const nodeByName = new Map<string, object>();
  for (const [node, name] of exportedSchemaName) nodeByName.set(name, node);
  const building = new Set<string>();
  let order = 0;

  const uniqueName = (hint: string, node: object): string => {
    let candidate = hint;
    let suffix = 2;
    while (nodeByName.has(candidate) && nodeByName.get(candidate) !== node) {
      candidate = `${hint}${suffix}`;
      suffix += 1;
    }
    return candidate;
  };

  const ensureModel = (name: string, node: AnySchema): void => {
    if (models.has(name) || building.has(name)) return;
    building.add(name);
    const required = requiredSet(node);
    const properties = propertiesOf(node);
    const fields: PyField[] = [];
    const deps = new Set<string>();
    const imports = new Set<string>();
    for (const key of schemaKeys(properties)) {
      const child = properties[key] as AnySchema;
      const resolved = pyTypeOf(child, `${name}${pascalCase(key)}`);
      for (const dep of resolved.deps) deps.add(dep);
      for (const imported of resolved.imports) imports.add(imported);
      fields.push({ name: key, type: resolved.expr, optional: !required.has(key) });
    }
    building.delete(name);
    models.set(name, {
      name,
      fields,
      forbidExtra: node['additionalProperties'] === false,
      deps,
      order: order++,
    });
    modelImports.set(name, imports);
  };

  const modelImports = new Map<string, Set<string>>();

  const pyTypeOf = (node: AnySchema, hint: string): PyTypeResult => {
    const known = lookupName(node, nameByNode, exportedSchemaByStructure);
    if (known) {
      ensureModelForNamed(known, (nodeByName.get(known) as AnySchema | undefined) ?? node);
      return { expr: known, deps: new Set([known]), imports: new Set() };
    }

    if ('const' in node && node['const'] !== undefined) {
      return {
        expr: `Literal[${pyLiteral(node['const'])}]`,
        deps: new Set(),
        imports: new Set(['Literal']),
      };
    }

    const anyOf = node['anyOf'];
    if (Array.isArray(anyOf)) {
      const members = anyOf.filter(isSchemaObject);
      const nullable = members.some(
        (member) => member['type'] === 'null' && schemaKeys(member).length === 1,
      );
      const rest = members.filter(
        (member) => !(member['type'] === 'null' && schemaKeys(member).length === 1),
      );
      const deps = new Set<string>();
      const imports = new Set<string>();
      let expr: string;
      if (rest.length === 0) {
        expr = 'None';
      } else if (rest.every((member) => 'const' in member && member['const'] !== undefined)) {
        imports.add('Literal');
        expr = `Literal[${rest.map((member) => pyLiteral(member['const'])).join(', ')}]`;
      } else {
        const parts = rest.map((member, index) => {
          const memberHint = rest.length === 1 ? hint : `${hint}Variant${index + 1}`;
          const resolved = pyTypeOf(member, memberHint);
          for (const dep of resolved.deps) deps.add(dep);
          for (const imported of resolved.imports) imports.add(imported);
          return resolved.expr;
        });
        if (parts.length === 1) {
          expr = parts[0] as string;
        } else {
          imports.add('Union');
          expr = `Union[${parts.join(', ')}]`;
        }
      }
      if (nullable && expr !== 'None') expr = `${expr} | None`;
      return { expr, deps, imports };
    }

    const type = node['type'];
    if (type === 'null') return { expr: 'None', deps: new Set(), imports: new Set() };
    if (type === 'boolean') return { expr: 'bool', deps: new Set(), imports: new Set() };

    if (type === 'string') {
      const format = node['format'];
      if (typeof format === 'string' && !PY_IGNORED_FORMATS.has(format)) {
        const alias = PY_FORMAT_ALIASES[format];
        if (alias === undefined) {
          throw new Error(
            `Unhandled string format '${format}'. Add it to PY_FORMAT_ALIASES (and to ` +
              'src/formats.ts) or to PY_IGNORED_FORMATS if it is a transport hint only.',
          );
        }
        usedAliases.add(alias);
        // The alias already carries the format's pattern; anything else the
        // schema declares still applies on top of it.
        const extra = pyFieldArguments(node).filter((arg) => !arg.startsWith('pattern='));
        if (extra.length === 0) return { expr: alias, deps: new Set(), imports: new Set() };
        return {
          expr: annotate(alias, extra),
          deps: new Set(),
          imports: new Set(['Annotated', 'Field']),
        };
      }
      const args = pyFieldArguments(node);
      return {
        expr: annotate('str', args),
        deps: new Set(),
        imports: new Set(args.length > 0 ? ['Annotated', 'Field'] : []),
      };
    }

    if (type === 'integer' || type === 'number') {
      const args = pyFieldArguments(node);
      return {
        expr: annotate(type === 'integer' ? 'int' : 'float', args),
        deps: new Set(),
        imports: new Set(args.length > 0 ? ['Annotated', 'Field'] : []),
      };
    }

    if (type === 'array') {
      const args = pyFieldArguments(node);
      const items = node['items'];
      const inner = isSchemaObject(items)
        ? pyTypeOf(items, `${hint}Item`)
        : { expr: 'Any', deps: new Set<string>(), imports: new Set(['Any']) };
      const imports = new Set<string>(inner.imports);
      if (args.length > 0) {
        imports.add('Annotated');
        imports.add('Field');
      }
      return { expr: annotate(`list[${inner.expr}]`, args), deps: inner.deps, imports };
    }

    if (type === 'object') {
      if (Object.keys(propertiesOf(node)).length > 0) {
        const name = uniqueName(hint, node);
        nameByNode.set(node, name);
        nodeByName.set(name, node);
        ensureModel(name, node);
        return { expr: name, deps: new Set([name]), imports: new Set() };
      }
      const patternProperties = node['patternProperties'];
      if (isPlainObject(patternProperties)) {
        const first = schemaKeys(patternProperties)[0];
        if (first !== undefined && isSchemaObject(patternProperties[first])) {
          const resolved = pyTypeOf(patternProperties[first] as AnySchema, `${hint}Value`);
          return {
            expr: `dict[str, ${resolved.expr}]`,
            deps: resolved.deps,
            imports: resolved.imports,
          };
        }
      }
      const additional = node['additionalProperties'];
      if (isSchemaObject(additional)) {
        const resolved = pyTypeOf(additional, `${hint}Value`);
        return {
          expr: `dict[str, ${resolved.expr}]`,
          deps: resolved.deps,
          imports: resolved.imports,
        };
      }
      return { expr: 'dict[str, Any]', deps: new Set(), imports: new Set(['Any']) };
    }

    // No `type`, no `anyOf`, no `const`: Type.Unknown().
    return { expr: 'Any', deps: new Set(), imports: new Set(['Any']) };
  };

  const ensureModelForNamed = (name: string, node: AnySchema): void => {
    ensureModel(name, node);
  };

  for (const [name, schema] of Object.entries(EXPORTED_SCHEMAS)) {
    ensureModel(name, schema as unknown as AnySchema);
  }

  /* Dependency (topological) ordering, deterministic by creation order. */
  const emitted: PyModel[] = [];
  const done = new Set<string>();
  const pending = [...models.values()].sort((a, b) => a.order - b.order);
  while (pending.length > 0) {
    const index = pending.findIndex((model) =>
      [...model.deps].every((dep) => dep === model.name || done.has(dep)),
    );
    if (index === -1) {
      throw new Error(
        `Cyclic schema dependency among: ${pending.map((model) => model.name).join(', ')}`,
      );
    }
    const [next] = pending.splice(index, 1);
    const model = next as PyModel;
    emitted.push(model);
    done.add(model.name);
  }

  const allImports = new Set<string>();
  for (const model of emitted) {
    for (const imported of modelImports.get(model.name) ?? []) allImports.add(imported);
  }

  const TYPING_NAMES = new Set(['Annotated', 'Any', 'Literal', 'Union']);
  const typingImports = [...allImports].filter((name) => TYPING_NAMES.has(name)).sort();
  const pydanticImports = new Set(['BaseModel', 'ConfigDict']);
  if (allImports.has('Field')) pydanticImports.add('Field');

  const wantsUuid = usedAliases.has('UuidString');
  const wantsTimestamp = usedAliases.has('TimestampString');
  if (wantsUuid || wantsTimestamp) {
    typingImports.push('Annotated');
    pydanticImports.add('Field');
  }
  if (wantsTimestamp) pydanticImports.add('AfterValidator');
  const sortedTypingImports = [...new Set(typingImports)].sort();

  const lines: string[] = [PY_HEADER];
  lines.push('"""Pydantic v2 models generated from the authoritative TypeBox contracts.');
  lines.push('');
  lines.push('Every JSON Schema constraint - pattern, length, range, item count and string');
  lines.push('format - is carried through, so a worker that validates with these models');
  lines.push('reaches the same verdict as the API, instead of only failing at the boundary.');
  lines.push('"""');
  lines.push('');
  const stdlibImports: string[] = [];
  if (wantsTimestamp) stdlibImports.push('from datetime import datetime');
  if (sortedTypingImports.length > 0) {
    stdlibImports.push(`from typing import ${sortedTypingImports.join(', ')}`);
  }
  if (stdlibImports.length > 0) {
    lines.push(...stdlibImports);
    lines.push('');
  }
  lines.push(`from pydantic import ${[...pydanticImports].sort().join(', ')}`);

  if (wantsUuid || wantsTimestamp) {
    const patterns = readFormatPatterns();
    lines.push('');
    if (wantsTimestamp) {
      lines.push('');
      lines.push('def _validate_utc_timestamp(value: str) -> str:');
      lines.push('    # The pattern fixes the shape and the UTC-only offset. This additionally');
      lines.push(
        '    # rejects instants the calendar does not allow, such as 2026-02-30T00:00:00Z,',
      );
      lines.push('    # matching what registerContractFormats() enforces on the TypeScript side.');
      lines.push('    try:');
      lines.push('        datetime.fromisoformat(value)');
      lines.push('    except ValueError as error:');
      lines.push('        raise ValueError("not a valid UTC ISO-8601 instant") from error');
      lines.push('    return value');
      lines.push('');
    }
    lines.push('');
    lines.push('# Mirrored from packages/contracts/src/formats.ts so both runtimes agree.');
    if (wantsUuid) {
      lines.push(...pyRawStringAssignment('_UUID_PATTERN', patterns.uuid));
      lines.push('UuidString = Annotated[str, Field(pattern=_UUID_PATTERN)]');
    }
    if (wantsTimestamp) {
      lines.push(...pyRawStringAssignment('_TIMESTAMP_PATTERN', patterns.dateTime));
      lines.push('TimestampString = Annotated[');
      lines.push('    str,');
      lines.push('    Field(pattern=_TIMESTAMP_PATTERN),');
      lines.push('    AfterValidator(_validate_utc_timestamp),');
      lines.push(']');
    }
  }

  for (const model of emitted) {
    lines.push('');
    lines.push('');
    lines.push(`class ${model.name}(BaseModel):`);
    const configEntries: string[] = [];
    if (model.forbidExtra) configEntries.push('extra="forbid"');
    if (model.fields.some((field) => field.name.startsWith('model_'))) {
      configEntries.push('protected_namespaces=()');
    }
    if (configEntries.length > 0) {
      lines.push(`    model_config = ConfigDict(${configEntries.join(', ')})`);
      if (model.fields.length > 0) lines.push('');
    }
    if (model.fields.length === 0 && configEntries.length === 0) {
      lines.push('    pass');
      continue;
    }
    for (const field of model.fields) {
      const annotation = field.optional ? nullable(field.type) : field.type;
      lines.push(...pyFieldLines(field.name, annotation, field.optional));
    }
  }
  lines.push('');

  const modelsSource = lines.join('\n');

  /* enums.py */
  const enumLines: string[] = [PY_HEADER];
  enumLines.push('"""String enumerations generated from the authoritative TypeBox contracts."""');
  enumLines.push('');
  enumLines.push('from enum import StrEnum');
  const enumNames = Object.keys(EXPORTED_ENUMS);
  for (const name of enumNames) {
    enumLines.push('');
    enumLines.push('');
    enumLines.push(`class ${name}(StrEnum):`);
    const values = EXPORTED_ENUMS[name] as readonly string[];
    if (values.length === 0) {
      enumLines.push('    pass');
      continue;
    }
    for (const value of values) {
      enumLines.push(`    ${screamingSnakeCase(value)} = ${JSON.stringify(value)}`);
    }
  }
  enumLines.push('');

  /* constants.py */
  const constantLines: string[] = [PY_HEADER];
  constantLines.push('"""Shared constants generated from the authoritative TypeBox contracts."""');
  constantLines.push('');
  constantLines.push('from typing import Final');
  constantLines.push('');
  const constantNames = Object.keys(EXPORTED_CONSTANTS);
  for (const name of constantNames) {
    const value = (EXPORTED_CONSTANTS as Record<string, unknown>)[name];
    if (Array.isArray(value)) {
      const items = value.map((entry) => pyLiteral(entry));
      const tuple = items.length === 1 ? `(${items[0]},)` : `(${items.join(', ')})`;
      const oneLine = `${name}: Final = ${tuple}`;
      if (oneLine.length <= PY_LINE_LENGTH) {
        constantLines.push(oneLine);
      } else {
        // Wrap rather than emit a line Ruff will reject. A trailing comma on
        // the last item keeps `ruff format` from collapsing it back.
        constantLines.push(`${name}: Final = (`);
        for (const item of items) constantLines.push(`    ${item},`);
        constantLines.push(')');
      }
    } else {
      constantLines.push(`${name}: Final = ${pyLiteral(value)}`);
    }
  }
  constantLines.push('');

  /* __init__.py */
  const modelNames = emitted.map((model) => model.name);
  // The constrained string aliases live alongside the models so a worker can
  // validate a bare uuid or timestamp with the same rule the models use.
  const aliasNames = [...usedAliases].sort();
  const exportable = [...modelNames, ...aliasNames, ...enumNames, ...constantNames];
  // Ruff's RUF022 "isort-style" __all__ ordering: SCREAMING_SNAKE constants
  // first, then the CamelCase names, each group sorted.
  const allNames = [
    ...exportable.filter((name) => /^[A-Z0-9_]+$/.test(name)).sort(),
    ...exportable.filter((name) => !/^[A-Z0-9_]+$/.test(name)).sort(),
  ];
  const initLines: string[] = [PY_HEADER];
  initLines.push('"""Generated contract bindings for the Job Getter Python worker."""');
  initLines.push('');
  initLines.push(`from .constants import (`);
  for (const name of [...constantNames].sort()) initLines.push(`    ${name},`);
  initLines.push(')');
  initLines.push(`from .enums import (`);
  for (const name of [...enumNames].sort()) initLines.push(`    ${name},`);
  initLines.push(')');
  initLines.push(`from .models import (`);
  for (const name of [...modelNames, ...aliasNames].sort()) initLines.push(`    ${name},`);
  initLines.push(')');
  initLines.push('');
  initLines.push('__all__ = [');
  for (const name of allNames) initLines.push(`    ${JSON.stringify(name)},`);
  initLines.push(']');
  initLines.push('');

  return {
    models: modelsSource,
    enums: enumLines.join('\n'),
    constants: constantLines.join('\n'),
    init: initLines.join('\n'),
    modelNames,
    aliasNames,
    enumNames,
    constantNames,
  };
}

/** Add `| None` without producing `None | None` or a redundant `Any | None`. */
function nullable(expr: string): string {
  if (expr === 'None' || expr === 'Any') return expr;
  if (expr.endsWith(' | None')) return expr;
  return `${expr} | None`;
}

const PY_LINE_LENGTH = 100;

/** Split a bracket body on top-level commas. */
function splitTopLevel(body: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let quote: string | null = null;
  let current = '';
  for (const char of body) {
    if (quote !== null) {
      current += char;
      if (char === quote) quote = null;
      continue;
    }
    if (char === '"' || char === "'") {
      quote = char;
      current += char;
      continue;
    }
    if (char === '[' || char === '(') depth += 1;
    if (char === ']' || char === ')') depth -= 1;
    if (char === ',' && depth === 0) {
      parts.push(current.trim());
      current = '';
      continue;
    }
    current += char;
  }
  if (current.trim().length > 0) parts.push(current.trim());
  return parts;
}

/**
 * Render one Pydantic field, wrapping oversized `Literal[...]`/`Union[...]`
 * annotations inside their brackets so generated output stays within the Ruff
 * line length configured in services/worker/pyproject.toml.
 */
function wrapPyType(annotation: string, indent: string, overhead = 0): string[] {
  if (indent.length + overhead + annotation.length <= PY_LINE_LENGTH) {
    return [indent + annotation];
  }
  const match = /^(Annotated|Literal|Union|list|dict)\[(.*)\]((?: \| None)?)$/s.exec(annotation);
  if (!match) return [indent + annotation];
  const head = match[1] as string;
  const body = match[2] as string;
  const tail = match[3] as string;
  const parts = splitTopLevel(body);
  if (parts.length === 0) return [indent + annotation];

  const out = [`${indent}${head}[`];
  parts.forEach((part, index) => {
    const nested = wrapPyType(part, `${indent}    `, index < parts.length - 1 ? 1 : 0);
    if (index < parts.length - 1) {
      nested[nested.length - 1] = `${nested[nested.length - 1] as string},`;
    }
    out.push(...nested);
  });
  out.push(`${indent}]${tail}`);
  return out;
}

function pyFieldLines(name: string, annotation: string, hasDefault: boolean): string[] {
  const suffix = hasDefault ? ' = None' : '';
  const single = `    ${name}: ${annotation}${suffix}`;
  if (single.length <= PY_LINE_LENGTH) return [single];

  const wrapped = wrapPyType(annotation, '    ', name.length + 2 + suffix.length);
  if (wrapped.length === 1) return [single];
  wrapped[0] = `    ${name}: ${(wrapped[0] as string).trimStart()}`;
  wrapped[wrapped.length - 1] = `${wrapped[wrapped.length - 1] as string}${suffix}`;
  return wrapped;
}

/* ------------------------------------------------------------------------- */
/* (d) Typed TypeScript client                                                */
/* ------------------------------------------------------------------------- */

interface TsTypeResult {
  readonly expr: string;
  readonly imports: ReadonlySet<string>;
}

function tsStringLiteral(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function tsLiteral(value: unknown): string {
  if (value === null) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  return tsStringLiteral(String(value));
}

function tsTypeOf(node: AnySchema): TsTypeResult {
  const name = lookupName(node, anyExportName, anyExportByStructure);
  if (name && EXPORTED_TYPE_NAMES.has(name)) {
    return { expr: name, imports: new Set([name]) };
  }

  if ('const' in node && node['const'] !== undefined) {
    return { expr: tsLiteral(node['const']), imports: new Set() };
  }

  const anyOf = node['anyOf'];
  if (Array.isArray(anyOf)) {
    const imports = new Set<string>();
    const parts = anyOf.filter(isSchemaObject).map((member) => {
      const resolved = tsTypeOf(member);
      for (const imported of resolved.imports) imports.add(imported);
      return resolved.expr;
    });
    return { expr: parts.length > 0 ? parts.join(' | ') : 'unknown', imports };
  }

  const type = node['type'];
  if (type === 'null') return { expr: 'null', imports: new Set() };
  if (type === 'string') return { expr: 'string', imports: new Set() };
  if (type === 'integer' || type === 'number') return { expr: 'number', imports: new Set() };
  if (type === 'boolean') return { expr: 'boolean', imports: new Set() };

  if (type === 'array') {
    const items = node['items'];
    if (isSchemaObject(items)) {
      const resolved = tsTypeOf(items);
      return { expr: `Array<${resolved.expr}>`, imports: resolved.imports };
    }
    return { expr: 'unknown[]', imports: new Set() };
  }

  if (type === 'object') {
    const properties = propertiesOf(node);
    const keys = schemaKeys(properties);
    if (keys.length > 0) {
      const required = requiredSet(node);
      const imports = new Set<string>();
      const members = keys.map((key) => {
        const resolved = tsTypeOf(properties[key] as AnySchema);
        for (const imported of resolved.imports) imports.add(imported);
        const optional = required.has(key) ? '' : '?';
        return `${key}${optional}: ${resolved.expr}`;
      });
      return { expr: `{ ${members.join('; ')} }`, imports };
    }
    const patternProperties = node['patternProperties'];
    if (isPlainObject(patternProperties)) {
      const first = schemaKeys(patternProperties)[0];
      if (first !== undefined && isSchemaObject(patternProperties[first])) {
        const resolved = tsTypeOf(patternProperties[first] as AnySchema);
        return { expr: `Record<string, ${resolved.expr}>`, imports: resolved.imports };
      }
    }
    const additional = node['additionalProperties'];
    if (isSchemaObject(additional)) {
      const resolved = tsTypeOf(additional);
      return { expr: `Record<string, ${resolved.expr}>`, imports: resolved.imports };
    }
    return { expr: 'Record<string, unknown>', imports: new Set() };
  }

  return { expr: 'unknown', imports: new Set() };
}

const CLIENT_PREAMBLE = `
/**
 * Typed fetch client for the Job Getter API, generated from
 * \`packages/contracts/src/routes.ts\`. One method per route operationId.
 *
 * Authentication is the HttpOnly session cookie, so every request is sent with
 * \`credentials: 'include'\`. Mutating routes additionally carry the anti-CSRF
 * token returned by \`getCsrfToken()\`, and the commands that the specification
 * marks as idempotent require an explicit \`idempotencyKey\` argument.
 */

export type FetchLike = (input: string, init?: RequestInit) => Promise<Response>;

export interface ApiClientOptions {
  /** Origin (and optional path prefix) the API is mounted on, e.g. \`https://localhost:8080\`. */
  readonly baseUrl: string;
  /** Injectable fetch implementation; defaults to \`globalThis.fetch\`. */
  readonly fetch?: FetchLike;
  /** Called once per 401 response, before the ApiError is thrown. */
  readonly onUnauthenticated?: () => void;
  /** Supplies the anti-CSRF token for routes that require one. */
  readonly getCsrfToken?: () => string | null | undefined;
}

/** Error envelope from 04_API_CONTRACTS.md. */
export interface ErrorEnvelopeBody {
  readonly error: {
    readonly code: string;
    readonly message: string;
    readonly fields?: Record<string, string>;
    readonly request_id?: string;
  };
}

/**
 * Thrown for every non-2xx response. \`code\` comes from the server envelope when
 * one was returned; a transport or non-JSON failure keeps the HTTP status and a
 * generic code rather than pretending the request succeeded.
 */
export class ApiError extends Error {
  readonly status: number;
  readonly code: ErrorCode | string;
  readonly fields: Record<string, string>;
  readonly requestId: string | null;

  constructor(init: {
    status: number;
    code: ErrorCode | string;
    message: string;
    fields?: Record<string, string>;
    requestId?: string | null;
  }) {
    super(init.message);
    this.name = 'ApiError';
    this.status = init.status;
    this.code = init.code;
    this.fields = init.fields ?? {};
    this.requestId = init.requestId ?? null;
  }

  static async fromResponse(response: Response): Promise<ApiError> {
    let payload: unknown;
    try {
      payload = await response.json();
    } catch {
      payload = undefined;
    }
    const envelope =
      typeof payload === 'object' && payload !== null && 'error' in payload
        ? (payload as ErrorEnvelopeBody).error
        : undefined;
    return new ApiError({
      status: response.status,
      code: envelope?.code ?? \`HTTP_\${response.status}\`,
      message: envelope?.message ?? \`Request failed with status \${response.status}\`,
      fields: envelope?.fields ?? {},
      requestId: envelope?.request_id ?? null,
    });
  }
}

type QueryValue = string | number | boolean | null | undefined;

interface RequestSpec {
  readonly method: string;
  readonly prefix: string;
  readonly path: string;
  readonly params?: Record<string, string>;
  readonly query?: Record<string, QueryValue>;
  readonly json?: unknown;
  readonly formData?: FormData;
  readonly csrf?: boolean;
  readonly idempotencyKey?: string;
  readonly binary?: boolean;
  readonly noContent?: boolean;
  readonly signal?: AbortSignal;
}

export class JobGetterApiClient {
  readonly #baseUrl: string;
  readonly #fetch: FetchLike;
  readonly #onUnauthenticated: (() => void) | undefined;
  readonly #getCsrfToken: (() => string | null | undefined) | undefined;

  constructor(options: ApiClientOptions) {
    this.#baseUrl = options.baseUrl.replace(/\\/+$/, '');
    this.#fetch = options.fetch ?? ((input, init) => globalThis.fetch(input, init));
    this.#onUnauthenticated = options.onUnauthenticated;
    this.#getCsrfToken = options.getCsrfToken;
  }

  async #request<T>(spec: RequestSpec): Promise<T> {
    let path = spec.path;
    for (const [key, value] of Object.entries(spec.params ?? {})) {
      path = path.replace(\`:\${key}\`, encodeURIComponent(String(value)));
    }

    let url = \`\${this.#baseUrl}\${spec.prefix}\${path}\`;
    const search = new URLSearchParams();
    for (const [key, value] of Object.entries(spec.query ?? {})) {
      if (value !== undefined && value !== null) search.append(key, String(value));
    }
    const queryString = search.toString();
    if (queryString.length > 0) url += \`?\${queryString}\`;

    const headers: Record<string, string> = {
      Accept: spec.binary ? 'application/octet-stream' : 'application/json',
    };
    let body: BodyInit | undefined;
    if (spec.formData !== undefined) {
      body = spec.formData;
    } else if (spec.json !== undefined) {
      headers['Content-Type'] = 'application/json';
      body = JSON.stringify(spec.json);
    }
    if (spec.csrf === true) {
      const token = this.#getCsrfToken?.();
      if (token !== undefined && token !== null && token !== '') headers['X-CSRF-Token'] = token;
    }
    if (spec.idempotencyKey !== undefined) headers['Idempotency-Key'] = spec.idempotencyKey;

    const response = await this.#fetch(url, {
      method: spec.method,
      credentials: 'include',
      headers,
      body,
      signal: spec.signal,
    });

    if (response.status === 401) this.#onUnauthenticated?.();
    if (!response.ok) throw await ApiError.fromResponse(response);
    if (spec.noContent === true || response.status === 204) return undefined as T;
    if (spec.binary === true) return (await response.blob()) as T;
    return (await response.json()) as T;
  }
`;

interface ClientBuild {
  readonly source: string;
}

export function buildClient(): ClientBuild {
  const typeImports = new Set<string>(['ErrorCode']);
  const aliases: string[] = [];
  const methods: string[] = [];

  const register = (result: TsTypeResult): string => {
    for (const imported of result.imports) typeImports.add(imported);
    return result.expr;
  };

  for (const route of ROUTES) {
    const base = pascalCase(route.operationId);
    const argsName = `${base}Args`;
    const resultName = `${base}Result`;

    const argMembers: string[] = [];
    let hasRequiredArg = false;

    if (route.params) {
      const expr = register(tsTypeOf(route.params as unknown as AnySchema));
      argMembers.push(`  /** Path parameters. */\n  readonly params: ${expr};`);
      hasRequiredArg = true;
    }
    if (route.query) {
      const expr = register(tsTypeOf(route.query as unknown as AnySchema));
      argMembers.push(`  /** Query string parameters. */\n  readonly query?: ${expr};`);
    }

    // A DELETE carries a body only when its route declares one; see
    // `deleteWorkspace` in src/routes.ts, whose password cannot go in a URL.
    const bodyless = route.method === 'GET' || (route.method === 'DELETE' && !route.body);
    const sendsEmptyBody = Boolean(route.body) && !bodyless && isEmptyClosedObject(route.body);
    const sendsBody = Boolean(route.body) && !bodyless && !sendsEmptyBody;
    if (sendsBody) {
      if (route.multipart) {
        argMembers.push(
          '  /** multipart/form-data payload; set the file part and its `purpose` field. */\n  readonly body: FormData;',
        );
      } else {
        const expr = register(tsTypeOf(route.body as unknown as AnySchema));
        argMembers.push(`  /** JSON request body. */\n  readonly body: ${expr};`);
      }
      hasRequiredArg = true;
    }
    if (route.requiresIdempotencyKey) {
      argMembers.push(
        '  /** Required: sent as the `Idempotency-Key` header (04_API_CONTRACTS.md). */\n  readonly idempotencyKey: string;',
      );
      hasRequiredArg = true;
    }
    argMembers.push('  readonly signal?: AbortSignal;');

    const returnExpr =
      route.successStatus === 204 || isNullSchema(route.response)
        ? 'void'
        : route.binaryResponse
          ? 'Blob'
          : register(tsTypeOf(route.response as unknown as AnySchema));

    aliases.push(
      `/** Arguments for \`${route.method} ${API_PREFIX}${route.path}\`. */\nexport interface ${argsName} {\n${argMembers.join('\n')}\n}`,
    );
    aliases.push(
      `/** Result of \`${camelCase(route.operationId)}\`. */\nexport type ${resultName} = ${returnExpr};`,
    );

    const specLines: string[] = [
      `      method: '${route.method}',`,
      `      prefix: API_PREFIX,`,
      `      path: ${tsStringLiteral(route.path)},`,
    ];
    if (route.params) specLines.push('      params: args.params,');
    if (route.query) specLines.push('      query: args.query,');
    if (sendsBody && route.multipart) specLines.push('      formData: args.body,');
    else if (sendsBody) specLines.push('      json: args.body,');
    else if (sendsEmptyBody) specLines.push('      json: {},');
    if (route.csrf) specLines.push('      csrf: true,');
    if (route.requiresIdempotencyKey) specLines.push('      idempotencyKey: args.idempotencyKey,');
    if (route.binaryResponse) specLines.push('      binary: true,');
    if (route.successStatus === 204 || isNullSchema(route.response)) {
      specLines.push('      noContent: true,');
    }
    specLines.push('      signal: args.signal,');

    const signature = hasRequiredArg ? `args: ${argsName}` : `args: ${argsName} = {}`;
    methods.push(
      [
        `  /** ${route.summary} (\`${route.method} ${API_PREFIX}${route.path}\`) */`,
        `  ${camelCase(route.operationId)}(${signature}): Promise<${resultName}> {`,
        `    return this.#request<${resultName}>({`,
        ...specLines,
        '    });',
        '  }',
      ].join('\n'),
    );
  }

  const importList = [...typeImports].sort();
  const source = [
    TS_HEADER,
    `import type {\n${importList.map((name) => `  ${name},`).join('\n')}\n} from '@job-getter/contracts';`,
    '',
    `/** Version prefix from \`packages/contracts/src/routes.ts\`. */`,
    `const API_PREFIX = ${tsStringLiteral(API_PREFIX)};`,
    '',
    CLIENT_PREAMBLE.trimStart().replace(/\n$/, ''),
    '',
    methods.join('\n\n'),
    '}',
    '',
    aliases.join('\n\n'),
    '',
  ].join('\n');

  return { source };
}

/* ------------------------------------------------------------------------- */
/* Artifact assembly                                                          */
/* ------------------------------------------------------------------------- */

function serializeJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function normalizeText(value: string): string {
  const withoutCr = value.replace(/\r\n/g, '\n');
  return withoutCr.endsWith('\n') ? withoutCr : `${withoutCr}\n`;
}

/** Absolute path -> exact file contents. Deterministic for a given source tree. */
export function buildArtifacts(): Map<string, string> {
  const artifacts = new Map<string, string>();

  for (const name of Object.keys(EXPORTED_SCHEMAS).sort()) {
    const schema = EXPORTED_SCHEMAS[name] as TSchema;
    artifacts.set(
      join(SCHEMA_DIR, `${name}.schema.json`),
      serializeJson(buildJsonSchemaDocument(name, schema)),
    );
  }

  artifacts.set(OPENAPI_FILE, serializeJson(buildOpenApiDocument()));

  const python = buildPython();
  artifacts.set(join(PYTHON_DIR, 'models.py'), normalizeText(python.models));
  artifacts.set(join(PYTHON_DIR, 'enums.py'), normalizeText(python.enums));
  artifacts.set(join(PYTHON_DIR, 'constants.py'), normalizeText(python.constants));
  artifacts.set(join(PYTHON_DIR, '__init__.py'), normalizeText(python.init));

  artifacts.set(CLIENT_FILE, normalizeText(buildClient().source));

  return new Map([...artifacts.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1)));
}

function listExistingManagedFiles(): string[] {
  const found: string[] = [];
  // Build caches are not artifacts; they must not look like drift.
  const IGNORED_DIRECTORIES = new Set(['__pycache__', '.mypy_cache', '.ruff_cache']);
  const walk = (dir: string): void => {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!IGNORED_DIRECTORIES.has(entry.name)) walk(full);
      } else if (!entry.name.endsWith('.pyc')) {
        found.push(full);
      }
    }
  };
  for (const dir of MANAGED_DIRECTORIES) walk(dir);
  if (existsSync(OPENAPI_FILE) && statSync(OPENAPI_FILE).isFile()) found.push(OPENAPI_FILE);
  return found.sort();
}

function displayPath(absolute: string): string {
  return relative(REPO_ROOT, absolute).split(sep).join(posix.sep);
}

export interface DriftEntry {
  readonly file: string;
  readonly status: 'missing' | 'changed' | 'unexpected';
  readonly detail?: string;
}

function firstDifference(expected: string, actual: string): string {
  const expectedLines = expected.split('\n');
  const actualLines = actual.split('\n');
  const limit = Math.max(expectedLines.length, actualLines.length);
  for (let index = 0; index < limit; index += 1) {
    if (expectedLines[index] !== actualLines[index]) {
      return [
        `first difference at line ${index + 1}`,
        `  generated: ${JSON.stringify(expectedLines[index] ?? '<end of file>')}`,
        `  on disk:   ${JSON.stringify(actualLines[index] ?? '<end of file>')}`,
      ].join('\n');
    }
  }
  return 'contents differ only in trailing whitespace';
}

/** Regenerate in memory and report every on-disk difference. */
export function checkArtifacts(): DriftEntry[] {
  const artifacts = buildArtifacts();
  const drift: DriftEntry[] = [];

  for (const [path, expected] of artifacts) {
    if (!existsSync(path)) {
      drift.push({ file: displayPath(path), status: 'missing' });
      continue;
    }
    const actual = readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
    if (actual !== expected) {
      drift.push({
        file: displayPath(path),
        status: 'changed',
        detail: firstDifference(expected, actual),
      });
    }
  }

  for (const path of listExistingManagedFiles()) {
    if (!artifacts.has(path)) {
      drift.push({ file: displayPath(path), status: 'unexpected' });
    }
  }

  return drift;
}

export function writeArtifacts(): { written: string[]; removed: string[] } {
  const artifacts = buildArtifacts();
  const written: string[] = [];
  const removed: string[] = [];

  for (const path of listExistingManagedFiles()) {
    if (!artifacts.has(path)) {
      rmSync(path);
      removed.push(displayPath(path));
    }
  }

  for (const [path, contents] of artifacts) {
    mkdirSync(dirname(path), { recursive: true });
    const current = existsSync(path) ? readFileSync(path, 'utf8').replace(/\r\n/g, '\n') : null;
    if (current !== contents) writeFileSync(path, contents, 'utf8');
    written.push(displayPath(path));
  }

  return { written, removed };
}

/* ------------------------------------------------------------------------- */
/* CLI                                                                       */
/* ------------------------------------------------------------------------- */

function main(argv: string[]): number {
  if (argv.includes('--check')) {
    const drift = checkArtifacts();
    if (drift.length === 0) {
      console.log(
        `contracts: generated artifacts are up to date (${buildArtifacts().size} files).`,
      );
      return 0;
    }
    console.error('contracts: generated artifacts are out of date.\n');
    for (const entry of drift) {
      console.error(`  ${entry.status.toUpperCase().padEnd(10)} ${entry.file}`);
      if (entry.detail) {
        for (const line of entry.detail.split('\n')) console.error(`    ${line}`);
      }
    }
    console.error('\nRun `pnpm contracts:generate` and commit the result.');
    return 1;
  }

  const { written, removed } = writeArtifacts();
  for (const file of removed) console.log(`removed ${file}`);
  console.log(`contracts: wrote ${written.length} generated files.`);
  return 0;
}

const invokedDirectly =
  process.argv[1] !== undefined && pathToFileURL(resolve(process.argv[1])).href === import.meta.url;

if (invokedDirectly) {
  process.exitCode = main(process.argv.slice(2));
}
