import { readFileSync, writeFileSync } from 'node:fs';
import { beforeAll, describe, expect, it } from 'vitest';
import {
  buildArtifacts,
  buildClient,
  buildJsonSchemaDocument,
  buildPython,
  checkArtifacts,
  writeArtifacts,
} from '../scripts/generate.js';
import { EXPORTED_CONSTANTS, EXPORTED_ENUMS, EXPORTED_SCHEMAS } from '../src/exports.js';
import { ROUTES } from '../src/routes.js';

describe('generator determinism and drift gate', () => {
  beforeAll(() => {
    // The drift gate only means something if the on-disk artifacts were
    // produced by this exact source tree.
    writeArtifacts();
  });

  it('produces byte-identical output when run twice', () => {
    const first = buildArtifacts();
    const second = buildArtifacts();
    expect([...second.keys()]).toEqual([...first.keys()]);
    for (const [path, contents] of first) {
      expect(second.get(path), path).toBe(contents);
    }
  });

  it('--check reports no drift immediately after a generate', () => {
    expect(checkArtifacts()).toEqual([]);
  });

  it('detects drift when an artifact is edited by hand', () => {
    const artifacts = buildArtifacts();
    const openapi = [...artifacts.keys()].find((path) => path.endsWith('openapi.json'))!;
    const original = readFileSync(openapi, 'utf8');
    try {
      writeFileSync(openapi, original.replace('"3.1.0"', '"3.0.0"'), 'utf8');
      const drift = checkArtifacts();
      expect(drift.length).toBeGreaterThan(0);
      expect(drift[0]!.status).toBe('changed');
      expect(drift[0]!.detail).toContain('first difference at line');
    } finally {
      writeFileSync(openapi, original, 'utf8');
    }
    expect(checkArtifacts()).toEqual([]);
  });

  it('every generated file ends with a newline and uses LF only', () => {
    for (const [path, contents] of buildArtifacts()) {
      expect(contents.endsWith('\n'), path).toBe(true);
      expect(contents.includes('\r'), path).toBe(false);
    }
  });
});

describe('generated JSON Schema documents', () => {
  it('emits one draft 2020-12 document per exported schema', () => {
    const artifacts = buildArtifacts();
    for (const name of Object.keys(EXPORTED_SCHEMAS)) {
      // Match the whole basename, separator included: a bare suffix match let
      // `SourceView` resolve to `JobSourceView.schema.json`. Keys carry the
      // host's separator, so normalise before comparing.
      const path = [...artifacts.keys()].find((candidate) =>
        candidate.replace(/\\/g, '/').endsWith(`/${name}.schema.json`),
      );
      expect(path, `no document for ${name}`).toBeDefined();
      const document = JSON.parse(artifacts.get(path!)!) as Record<string, unknown>;
      expect(document['$schema']).toBe('https://json-schema.org/draft/2020-12/schema');
      expect(document['$id']).toBe(`https://job-getter.local/schemas/${name}.schema.json`);
      expect(document['title']).toBe(name);
      expect(document['type']).toBe('object');
    }
  });

  it('carries no TypeBox internal keys', () => {
    const document = buildJsonSchemaDocument('Preferences', EXPORTED_SCHEMAS['Preferences']!);
    const serialized = JSON.stringify(document);
    expect(serialized).not.toContain('Kind');
    expect(Object.getOwnPropertySymbols(document)).toHaveLength(0);
  });
});

describe('generated Pydantic models', () => {
  const python = buildPython();

  it('starts every module with the do-not-edit header', () => {
    for (const source of [python.models, python.enums, python.constants, python.init]) {
      expect(source.split('\n')[0]).toBe(
        '# Generated by packages/contracts/scripts/generate.ts. Do not edit by hand.',
      );
    }
  });

  it('emits one model per exported schema', () => {
    for (const name of Object.keys(EXPORTED_SCHEMAS)) {
      expect(python.models, name).toContain(`class ${name}(BaseModel):`);
    }
  });

  it('emits models in dependency order', () => {
    const position = (name: string): number => python.models.indexOf(`class ${name}(BaseModel):`);
    expect(position('ContactValue')).toBeLessThan(position('Profile'));
    expect(position('ProfileFact')).toBeLessThan(position('Profile'));
    expect(position('MatchWeights')).toBeLessThan(position('Preferences'));
    expect(position('Preferences')).toBeLessThan(position('PreferencesView'));
    expect(position('TaskInputFile')).toBeLessThan(position('ClaimResponse'));
  });

  it('reuses an exported model instead of duplicating an optional-wrapped copy', () => {
    expect(python.models).toContain('contact: ContactValue | None = None');
    expect(python.models).not.toContain('class ProfilePatchRequestContact');
    expect(python.models).toContain('progress: TaskProgress | None = None');
  });

  it('forbids extra keys wherever the source schema closes the object', () => {
    const blocks = python.models.split('\nclass ').slice(1);
    for (const block of blocks) {
      const name = block.slice(0, block.indexOf('('));
      if (!(name in EXPORTED_SCHEMAS)) continue;
      const source = EXPORTED_SCHEMAS[name] as unknown as Record<string, unknown>;
      if (source['additionalProperties'] === false) {
        expect(block, name).toContain('extra="forbid"');
      }
    }
  });

  it('maps optional properties to a nullable annotation with a default, keeping constraints', () => {
    expect(python.models).toContain('note: Annotated[str, Field(max_length=300)] | None = None');
    expect(python.models).toContain(
      'delay_ms: Annotated[int, Field(ge=0, le=60000)] | None = None',
    );
    // An unconstrained optional stays bare rather than gaining an empty Field().
    expect(python.models).toContain('task_id: UuidString | None');
    expect(python.models).not.toContain('Field()');
  });

  it('emits a StrEnum per exported enum with every member', () => {
    for (const [name, values] of Object.entries(EXPORTED_ENUMS)) {
      expect(python.enums).toContain(`class ${name}(StrEnum):`);
      for (const value of values) expect(python.enums).toContain(`= "${value}"`);
    }
  });

  it('emits every shared constant, with tuples for array values', () => {
    for (const [name, value] of Object.entries(EXPORTED_CONSTANTS)) {
      expect(python.constants).toContain(`${name}: Final =`);
      if (Array.isArray(value)) {
        expect(python.constants).toContain(`${name}: Final = (`);
      }
    }
    // Derived from the contract rather than hard-coded, so adding a task type
    // does not turn this into a test of yesterday's list. The members are
    // asserted rather than the exact layout, because a tuple long enough to
    // exceed the Ruff line length is emitted one item per line.
    const implemented = EXPORTED_CONSTANTS.IMPLEMENTED_TASK_TYPES as readonly string[];
    const start = python.constants.indexOf('IMPLEMENTED_TASK_TYPES: Final =');
    expect(start).toBeGreaterThanOrEqual(0);
    const rest = python.constants.slice(start);
    // Up to the next constant, which is the next line starting at column zero
    // with a name rather than a closing bracket or an indented member.
    const end = rest.search(/\n[A-Z_]+: Final/);
    const block = end === -1 ? rest : rest.slice(0, end);
    for (const type of implemented) expect(block).toContain(`"${type}"`);
    // Both browser tasks are runner-only: a headless container has no desktop
    // browser, and neither of these may ever be claimed by one.
    expect(python.constants).toContain(
      'RUNNER_ONLY_CAPABILITIES: Final = ("fill_local", "observe_confirmation")',
    );
  });

  it('re-exports everything from __init__ with an __all__ entry', () => {
    expect(python.aliasNames).toContain('UuidString');
    expect(python.aliasNames).toContain('TimestampString');
    const names = [
      ...python.modelNames,
      ...python.aliasNames,
      ...python.enumNames,
      ...python.constantNames,
    ];
    for (const name of names) {
      expect(python.init, name).toContain(`    ${name},`);
      expect(python.init, name).toContain(`    "${name}",`);
    }
  });

  it('keeps every generated line inside the Ruff line length', () => {
    for (const source of [python.models, python.enums, python.constants, python.init]) {
      for (const [index, line] of source.split('\n').entries()) {
        expect(line.length, `line ${index + 1}: ${line}`).toBeLessThanOrEqual(100);
      }
    }
  });
});

describe('generated TypeScript client', () => {
  const source = buildClient().source;

  it('exposes one method per route', () => {
    for (const route of ROUTES) {
      expect(source, route.operationId).toContain(`  ${route.operationId}(args:`);
    }
  });

  it('requires an idempotencyKey argument exactly on the idempotent commands', () => {
    for (const route of ROUTES) {
      const block = source.slice(
        source.indexOf(`export interface ${capitalize(route.operationId)}Args`),
      );
      const args = block.slice(0, block.indexOf('\n}'));
      expect(args.includes('readonly idempotencyKey: string;'), route.operationId).toBe(
        Boolean(route.requiresIdempotencyKey),
      );
    }
  });

  it('sends the CSRF header only on routes that declare it', () => {
    for (const route of ROUTES) {
      const start = source.indexOf(`  ${route.operationId}(args:`);
      const body = source.slice(start, source.indexOf('\n  }', start));
      expect(body.includes('csrf: true'), route.operationId).toBe(Boolean(route.csrf));
    }
  });

  it('returns Blob for binary routes and void for 204 routes', () => {
    for (const route of ROUTES) {
      const alias = `export type ${capitalize(route.operationId)}Result = `;
      const value = source.slice(source.indexOf(alias) + alias.length);
      const declared = value.slice(0, value.indexOf(';'));
      if (route.binaryResponse) expect(declared).toBe('Blob');
      if (route.successStatus === 204) expect(declared).toBe('void');
    }
  });

  it('takes FormData for multipart routes', () => {
    expect(source).toContain('readonly body: FormData;');
    expect(source).toContain('formData: args.body,');
  });

  it('always sends credentials and parses the error envelope', () => {
    expect(source).toContain("credentials: 'include'");
    expect(source).toContain('export class ApiError extends Error');
    expect(source).toContain('requestId');
    expect(source).toContain('this.#onUnauthenticated?.()');
  });

  it('imports contract types rather than redeclaring them', () => {
    expect(source).toContain("} from '@job-getter/contracts';");
    expect(source).toContain('export type GetProfileResult = Profile;');
  });
});

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
