<#
.SYNOPSIS
    Start the local development loop without full Docker Compose.

.DESCRIPTION
    PowerShell equivalent of scripts/dev.sh.

    PostgreSQL runs in Docker (nobody wants to install it); the API, the web dev
    server and the Python worker run on the host with hot reload. That is the
    difference from `docker compose up`: instant reloads and a debugger, at the
    cost of the containers not matching production exactly.

    Use `docker compose up --build` when you want to test what actually ships.

    Starts:
      db      PostgreSQL 17 in Docker, PUBLISHED on 127.0.0.1:5432 so host
              processes can reach it (full Compose does not publish it)
      api     pnpm --filter @job-getter/api dev      (tsx watch, port 8080)
      web     pnpm --filter @job-getter/web dev      (vite, port 5173)
      worker  uv run --project services/worker job-getter-worker

.PARAMETER DbOnly
    Start only the database, then exit. Useful when you want to run the other
    processes yourself in separate terminals.

.PARAMETER NoWorker
    Skip the Python worker.

.PARAMETER NoWeb
    Skip the Vite dev server.

.PARAMETER NoApi
    Skip the API.

.NOTES
    * DATABASE_URL is rewritten from the Compose hostname `db` to 127.0.0.1
      automatically, because `db` does not resolve on your host.
    * WORKER_API_BASE_URL is likewise pointed at 127.0.0.1:8080.
    * Migrations are applied before the API starts.
    * Ctrl-C stops the host processes. The database container KEEPS RUNNING so
      your data survives; stop it with `docker compose stop db`.
    * Vite serves on 5173 in this mode, not 3000. 3000 is the Compose web
      container. scripts/smoke.ps1 defaults to 3000, so point it at the API
      for this loop, sending the Vite origin the API trusts here:
          powershell -ExecutionPolicy Bypass -File scripts/smoke.ps1 -BaseUrl http://127.0.0.1:8080 -Origin http://localhost:5173
    * The API listens on 127.0.0.1 only, as Compose publishes it (DEV_HOST to change).
    * $env:JG_DEV_DB_PORT moves the database's host port off 5432, for when
      another PostgreSQL already has it. DATABASE_URL is rewritten to match.
    * Everything else comes from .env, read as data rather than executed, as
      Compose's env_file would pass it. A variable already set in your shell
      wins.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts/dev.ps1

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts/dev.ps1 -DbOnly
#>
[CmdletBinding()]
param(
    [switch]$DbOnly,
    [switch]$NoWorker,
    [switch]$NoWeb,
    [switch]$NoApi
)

. "$PSScriptRoot\lib.ps1"

Set-Location $script:JGRepoRoot
Assert-JGCompose
Assert-JGFile -Path $script:JGEnvFile -Hint 'run scripts/setup.ps1 first'

# --- Database -----------------------------------------------------------------
# The host port is configurable because a contributor often has a PostgreSQL of
# their own on 5432 already. Inside the container it is always 5432.
$dbPort = '5432'
if ($env:JG_DEV_DB_PORT) { $dbPort = $env:JG_DEV_DB_PORT }
if ($dbPort -notmatch '^\d{1,5}$') { Stop-JG "JG_DEV_DB_PORT must be a port number, not '$dbPort'." }
Write-JGInfo "Starting PostgreSQL (published on 127.0.0.1:$dbPort for host access)"

# A tiny override written to a temp file rather than into the repository, so the
# dev loop can reach the database without anyone accidentally committing a
# published-database override to docker-compose.override.yml.
$devOverride = Join-Path $script:JGRepoRoot '.dev-compose.tmp.yml'
$overrideText = @"
# Generated by scripts/dev.ps1. Temporary; deleted immediately. Do not commit.
services:
  db:
    ports:
      - "127.0.0.1:${dbPort}:5432"
"@
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($devOverride, $overrideText, $utf8NoBom)

try {
    & docker compose -f docker-compose.yml -f $devOverride up -d --wait db
    if ($LASTEXITCODE -ne 0) {
        throw "the database did not start. If the output above says the port is already allocated, another PostgreSQL is using ${dbPort}: set `$env:JG_DEV_DB_PORT to a free port. Otherwise check: docker compose logs db"
    }
}
catch {
    Remove-Item -Force -LiteralPath $devOverride -ErrorAction SilentlyContinue
    Stop-JG $_.Exception.Message
}
finally {
    Remove-Item -Force -LiteralPath $devOverride -ErrorAction SilentlyContinue
}
Write-JGOk "database ready on 127.0.0.1:$dbPort"

if ($DbOnly) {
    Write-Host ''
    Write-Host 'Database only, as requested. It stays up until you run:'
    Write-Host '    docker compose stop db'
    exit 0
}

# --- Host-side environment ----------------------------------------------------
# Compose hands the whole of .env to the api and worker containers (env_file),
# and they refuse to start without its secrets. The host processes need the
# same, so .env is read here as data - KEY=VALUE lines, never executed - into
# this process's environment, which the processes below inherit. A variable
# already set in your shell wins, as it would for any single value.
$callerSet = @{}
foreach ($item in Get-ChildItem Env:) { $callerSet[$item.Name] = $true }
foreach ($line in Get-Content -LiteralPath $script:JGEnvFile -Encoding UTF8) {
    if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)=') {
        $key = $Matches[1]
        if (-not $callerSet.ContainsKey($key)) {
            Set-Item -Path "Env:$key" -Value (Get-JGEnvValue -Key $key)
        }
    }
}

# Then the values that differ on the host. Compose service names do not
# resolve here, and container paths do not exist.
$databaseUrl = Get-JGEnvValue -Key 'DATABASE_URL'
$databaseUrl = $databaseUrl -replace '@db(:\d+)?/', "@127.0.0.1:$dbPort/"
if (-not $databaseUrl) { Stop-JG 'DATABASE_URL is missing from .env' }
$env:DATABASE_URL = $databaseUrl

if (-not $callerSet.ContainsKey('WORKER_API_BASE_URL')) { $env:WORKER_API_BASE_URL = 'http://127.0.0.1:8080' }
if (-not $callerSet.ContainsKey('WORKER_ID'))           { $env:WORKER_ID = "dev-worker-$PID" }
if (-not $callerSet.ContainsKey('PORT'))                { $env:PORT = '8080' }
# The API binds 0.0.0.0 by default, which is right inside a container that
# Compose publishes on loopback only. On the host it would put the API on the
# network, so the dev loop keeps it on loopback. DEV_HOST overrides it, not an
# inherited HOST: zsh sets HOST to the machine's name.
if ($env:DEV_HOST) { $env:HOST = $env:DEV_HOST } else { $env:HOST = '127.0.0.1' }
# Vite's dev server origin, so cookies and origin verification line up.
if ($env:DEV_APP_ORIGIN) { $env:APP_ORIGIN = $env:DEV_APP_ORIGIN } else { $env:APP_ORIGIN = 'http://localhost:5173' }

if (-not $env:FILES_ROOT_DEV) { $env:FILES_ROOT = Join-Path $script:JGRepoRoot '.dev-files' }
else                          { $env:FILES_ROOT = $env:FILES_ROOT_DEV }
New-Item -ItemType Directory -Path $env:FILES_ROOT -Force | Out-Null

# --- Migrations ---------------------------------------------------------------
Write-JGInfo 'Applying migrations...'
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'migrate.ps1') -Local
if ($LASTEXITCODE -ne 0) { Stop-JG 'migrations failed; not starting anything else.' }

# --- Processes ----------------------------------------------------------------
$processes = @()

function Start-JGDevProcess {
    param(
        [Parameter(Mandatory)][string]$Label,
        [Parameter(Mandatory)][string]$FilePath,
        [Parameter(Mandatory)][string[]]$ArgumentList
    )
    Write-JGInfo "starting $Label : $FilePath $($ArgumentList -join ' ')"
    # npm-style installs put three files on PATH - pnpm, pnpm.cmd, pnpm.ps1 -
    # and Start-Process takes the extensionless one, a shell script Windows
    # cannot run ("not a valid Win32 application"). Resolve it to the .exe or
    # .cmd that PowerShell itself would run.
    $resolved = Get-Command $FilePath -CommandType Application -ErrorAction SilentlyContinue |
        Where-Object { @('.exe', '.cmd', '.bat') -contains [System.IO.Path]::GetExtension($_.Source).ToLower() } |
        Select-Object -First 1
    if ($resolved) { $FilePath = $resolved.Source }
    # -NoNewWindow so all output lands in this terminal, as the sh version does.
    $p = Start-Process -FilePath $FilePath -ArgumentList $ArgumentList `
                       -WorkingDirectory $script:JGRepoRoot -NoNewWindow -PassThru
    Write-JGOk "$Label pid $($p.Id)"
    return $p
}

if (-not $NoApi) {
    Assert-JGCommand -Name 'pnpm' -Hint 'Install pnpm: corepack enable; corepack prepare --activate'
    $processes += Start-JGDevProcess -Label 'api' -FilePath 'pnpm' -ArgumentList @('--filter', '@job-getter/api', 'dev')
}
if (-not $NoWeb) {
    Assert-JGCommand -Name 'pnpm' -Hint 'Install pnpm: corepack enable; corepack prepare --activate'
    $processes += Start-JGDevProcess -Label 'web' -FilePath 'pnpm' -ArgumentList @('--filter', '@job-getter/web', 'dev')
}
if (-not $NoWorker) {
    Assert-JGCommand -Name 'uv' -Hint 'Install uv: https://docs.astral.sh/uv/getting-started/installation/'
    # --project so it resolves services/worker/uv.lock regardless of cwd.
    # No --frozen here: a contributor editing pyproject.toml should get a clear
    # resolution error, not a stale environment.
    $processes += Start-JGDevProcess -Label 'worker' -FilePath 'uv' -ArgumentList @('run', '--project', 'services/worker', 'job-getter-worker')
}

Write-Host ''
Write-Host '-----------------------------------------------------------------------'
if (-not $NoWeb)    { Write-Host '  web     http://localhost:5173' }
if (-not $NoApi)    { Write-Host '  api     http://127.0.0.1:8080' }
Write-Host "  db      127.0.0.1:$dbPort"
if (-not $NoWorker) { Write-Host "  worker  $($env:WORKER_ID)" }
Write-Host ''
Write-Host '  Ctrl-C stops the host processes; the database keeps running.'
Write-Host '-----------------------------------------------------------------------'
Write-Host ''

# Wait for any child to exit, then take the rest down rather than leaving a
# half-running stack that looks healthy. Ctrl-C lands in the finally block.
try {
    while ($true) {
        $dead = @($processes | Where-Object { $_.HasExited })
        if ($dead.Count -gt 0) {
            Write-JGWarn "a development process exited (pid $($dead[0].Id)); shutting the rest down"
            break
        }
        Start-Sleep -Milliseconds 500
    }
}
finally {
    Write-Host ''
    Write-JGInfo 'Stopping development processes...'
    # The whole tree, not just the process started: pnpm.cmd is cmd.exe running
    # node running tsx or vite, and stopping only cmd.exe would leave the
    # servers running and holding their ports. (For a process that has already
    # exited, Windows no longer links its children to it, so /T finds nothing.)
    foreach ($p in $processes) {
        Invoke-JGNative { taskkill /T /F /PID $p.Id } | Out-Null
    }
    Write-Host ''
    Write-Host 'Host processes stopped. The database container is still running:'
    Write-Host '    docker compose stop db      # stop it'
    Write-Host '    docker compose down         # stop and remove (data preserved)'
}
