#!/usr/bin/env sh
# =============================================================================
# scripts/dev.sh - the contributor dev loop, without full Compose
#
# POSIX shell. PowerShell equivalent: scripts/dev.ps1
#
# PostgreSQL runs in Docker (nobody wants to install it); the API, the web dev
# server and the Python worker run on the host with hot reload. That is the
# difference from `docker compose up`: you get instant reloads and a debugger,
# at the cost of the containers not matching production exactly.
#
# Use `docker compose up --build` when you want to test what actually ships.
# =============================================================================
set -eu

. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)/lib.sh"

WITH_WORKER=1
WITH_WEB=1
WITH_API=1
DB_ONLY=0

usage() {
  cat <<'HELPTEXT'
scripts/dev.sh - start the local development loop

USAGE
    sh scripts/dev.sh [options]

WHAT IT STARTS
    db      PostgreSQL 17 in Docker, PUBLISHED on 127.0.0.1:5432 so host
            processes can reach it. (Full Compose does not publish it.)
    api     pnpm --filter @job-getter/api dev      (tsx watch, port 8080)
    web     pnpm --filter @job-getter/web dev      (vite, port 5173)
    worker  uv run --project services/worker job-getter-worker

OPTIONS
    --db-only      Start only the database, then exit. Useful when you want to
                   run the other processes yourself in separate terminals.
    --no-worker    Skip the Python worker.
    --no-web       Skip the Vite dev server.
    --no-api       Skip the API.
    -h, --help     Show this help and exit.

NOTES
    * DATABASE_URL is rewritten from the Compose hostname `db` to 127.0.0.1
      automatically, because `db` does not resolve on your host.
    * WORKER_API_BASE_URL is likewise pointed at 127.0.0.1:8080.
    * Migrations are applied before the API starts.
    * Ctrl-C stops the host processes. The database container KEEPS RUNNING so
      your data survives; stop it with `docker compose stop db`.
    * Vite serves on 5173 in this mode, not 3000. 3000 is the Compose web
      container. scripts/smoke.sh defaults to 3000, so point it at the API
      for this loop, sending the Vite origin the API trusts here:
          sh scripts/smoke.sh --base-url http://127.0.0.1:8080 --origin http://localhost:5173
    * The API listens on 127.0.0.1 only, as Compose publishes it (DEV_HOST to change).
    * JG_DEV_DB_PORT moves the database's host port off 5432, for when another
      PostgreSQL already has it. DATABASE_URL is rewritten to match.
    * Everything else comes from .env, read as data rather than sourced, as
      Compose's env_file would pass it. A variable already set in your shell
      wins.

EXIT STATUS
    0 on a clean shutdown; non-zero if a prerequisite is missing or a service
    failed to start.
HELPTEXT
}

while [ $# -gt 0 ]; do
  case "$1" in
    --db-only)   DB_ONLY=1 ;;
    --no-worker) WITH_WORKER=0 ;;
    --no-web)    WITH_WEB=0 ;;
    --no-api)    WITH_API=0 ;;
    -h|--help)   usage; exit 0 ;;
    *) usage >&2; die "unknown option: $1" ;;
  esac
  shift
done

cd "$JG_REPO_ROOT"
require_compose
require_file "$JG_ENV_FILE" "run 'sh scripts/setup.sh' first"

# --- Database -----------------------------------------------------------------
# The host port is configurable because a contributor often has a PostgreSQL of
# their own on 5432 already. Inside the container it is always 5432.
DB_PORT="${JG_DEV_DB_PORT:-5432}"
case "$DB_PORT" in
  ''|*[!0-9]*) die "JG_DEV_DB_PORT must be a port number, not '${DB_PORT}'." ;;
esac
info "Starting PostgreSQL (published on 127.0.0.1:${DB_PORT} for host access)"

# A tiny override, generated into a temp file rather than into the repository,
# so the dev loop can reach the database without anyone accidentally committing
# a published-database override to docker-compose.override.yml.
DEV_OVERRIDE="${JG_REPO_ROOT}/.dev-compose.tmp.yml"
cat > "$DEV_OVERRIDE" <<OVERRIDE
# Generated by scripts/dev.sh. Temporary; deleted on exit. Do not commit.
services:
  db:
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
OVERRIDE

COMPOSE="docker compose -f docker-compose.yml -f ${DEV_OVERRIDE}"

# shellcheck disable=SC2086
$COMPOSE up -d --wait db \
  || { rm -f "$DEV_OVERRIDE"; die "the database did not start. If the output above says the port is already allocated, another PostgreSQL is using ${DB_PORT}: set JG_DEV_DB_PORT to a free port. Otherwise check: docker compose logs db"; }
ok "database ready on 127.0.0.1:${DB_PORT}"

rm -f "$DEV_OVERRIDE"

if [ "$DB_ONLY" = "1" ]; then
  log ""
  log "Database only, as requested. It stays up until you run:"
  log "    docker compose stop db"
  exit 0
fi

# --- Host-side environment ----------------------------------------------------
# Compose service names do not resolve on the host; rewrite them.
DATABASE_URL=$(env_get DATABASE_URL || printf '')
DATABASE_URL=$(printf '%s' "$DATABASE_URL" | sed -E "s#@db(:[0-9]+)?/#@127.0.0.1:${DB_PORT}/#")
[ -n "$DATABASE_URL" ] || die "DATABASE_URL is missing from .env"
export DATABASE_URL

export WORKER_API_BASE_URL="${WORKER_API_BASE_URL:-http://127.0.0.1:8080}"
export WORKER_ID="${WORKER_ID:-dev-worker-$$}"
export PORT="${PORT:-8080}"
# The API binds 0.0.0.0 by default, which is right inside a container that
# Compose publishes on loopback only. On the host it would put the API on the
# network, so the dev loop keeps it on loopback. DEV_HOST overrides it, not an
# inherited HOST: zsh sets HOST to the machine's name.
export HOST="${DEV_HOST:-127.0.0.1}"
# Vite's dev server origin, so cookies and origin verification line up.
export APP_ORIGIN="${DEV_APP_ORIGIN:-http://localhost:5173}"

# Local file storage on the host, outside the repo tree would be tidier, but
# inside .gitignored build output keeps it discoverable and disposable.
export FILES_ROOT="${FILES_ROOT_DEV:-${JG_REPO_ROOT}/.dev-files}"
mkdir -p "$FILES_ROOT"

# Compose hands the whole of .env to the api and worker containers (env_file),
# and they refuse to start without its secrets. The host processes need the
# same, so the rest of .env is read here as data - one key at a time with
# env_get, never sourced - and exported for them. Anything already set wins:
# a variable from your shell, or a host value exported above.
for _key in $(sed -n 's/^[[:space:]]*\([A-Za-z_][A-Za-z0-9_]*\)=.*/\1/p' "$JG_ENV_FILE" | sort -u); do
  # The name matched [A-Za-z_][A-Za-z0-9_]*, so this eval only ever reads a
  # variable; the value itself is never evaluated.
  eval "_isset=\${${_key}+x}"
  [ -n "$_isset" ] || export "${_key}=$(env_get "$_key")"
done

# --- Migrations ---------------------------------------------------------------
info "Applying migrations..."
sh "${JG_SCRIPT_DIR}/migrate.sh" --local || die "migrations failed; not starting anything else."

# --- Process supervision ------------------------------------------------------
PIDS=""
stop_all() {
  printf '\n' >&2
  info "Stopping development processes..."
  for _p in $PIDS; do
    kill "$_p" 2>/dev/null || true
  done
  for _p in $PIDS; do
    wait "$_p" 2>/dev/null || true
  done
  log ""
  log "Host processes stopped. The database container is still running:"
  log "    docker compose stop db      # stop it"
  log "    docker compose down         # stop and remove (data preserved)"
  exit 0
}
trap stop_all INT TERM

start_bg() {
  _label=$1; shift
  info "starting ${_label}: $*"
  "$@" &
  _pid=$!
  PIDS="${PIDS} ${_pid}"
  ok "${_label} pid ${_pid}"
}

if [ "$WITH_API" = "1" ]; then
  require_cmd pnpm "Install pnpm: corepack enable && corepack prepare --activate"
  start_bg api pnpm --filter @job-getter/api dev
fi

if [ "$WITH_WEB" = "1" ]; then
  require_cmd pnpm "Install pnpm: corepack enable && corepack prepare --activate"
  start_bg web pnpm --filter @job-getter/web dev
fi

if [ "$WITH_WORKER" = "1" ]; then
  require_cmd uv "Install uv: https://docs.astral.sh/uv/getting-started/installation/"
  # --project so it resolves services/worker/uv.lock regardless of cwd.
  # No --frozen here: a contributor editing pyproject.toml should get a clear
  # resolution error, not a stale environment.
  start_bg worker uv run --project services/worker job-getter-worker
fi

log ""
log "-----------------------------------------------------------------------"
[ "$WITH_WEB" = "1" ]    && log "  web     http://localhost:5173"
[ "$WITH_API" = "1" ]    && log "  api     http://127.0.0.1:8080"
log "  db      127.0.0.1:${DB_PORT}"
[ "$WITH_WORKER" = "1" ] && log "  worker  ${WORKER_ID}"
log ""
log "  Ctrl-C stops the host processes; the database keeps running."
log "-----------------------------------------------------------------------"
log ""

# Wait for any child to exit. If one dies, take the rest down rather than
# leaving a half-running stack that looks healthy. Polled, not
# `wait -n || wait`: dash (sh on Debian and Ubuntu) has no `wait -n`, and in
# bash a child that exits non-zero - a crash, the case this is for - also fell
# through to the plain `wait`, which blocks until every child has exited.
_alive=1
while [ "$_alive" = "1" ]; do
  sleep 1
  for _p in $PIDS; do
    kill -0 "$_p" 2>/dev/null || { _alive=0; break; }
  done
done
warn "a development process exited; shutting the rest down"
stop_all
