<#
.SYNOPSIS
    Start the local development loop without full Docker Compose.

.DESCRIPTION
    PowerShell equivalent of scripts/dev.sh.

    PostgreSQL runs in Docker (nobody wants to install it); the API, the web dev
    server and the Python worker run on the host with hot reload. That is the
    difference from `docker compose up`: instant reloads and a debugger, at the
    cost of the containers not matching production exactly.

    Use `docker compose up --build` when you want to test what actually ships.

    Starts:
      db      PostgreSQL 17 in Docker, PUBLISHED on 127.0.0.1:5432 so host
              processes can reach it (full Compose does not publish it)
      api     pnpm --filter @job-getter/api dev      (tsx watch, port 8080)
      web     pnpm --filter @job-getter/web dev      (vite, port 5173)
      worker  uv run --project services/worker job-getter-worker

.PARAMETER DbOnly
    Start only the database, then exit. Useful when you want to run the other
    processes yourself in separate terminals.

.PARAMETER NoWorker
    Skip the Python worker.

.PARAMETER NoWeb
    Skip the Vite dev server.

.PARAMETER NoApi
    Skip the API.

.NOTES
    * DATABASE_URL is rewritten from the Compose hostname `db` to 127.0.0.1
      automatically, because `db` does not resolve on your host.
    * WORKER_API_BASE_URL is likewise pointed at 127.0.0.1:8080.
    * Migrations are applied before the API starts.
    * Ctrl-C stops the host processes. The database container KEEPS RUNNING so
      your data survives; stop it with `docker compose stop db`.
    * Vite serves on 5173 in this mode, not 3000. 3000 is the Compose web
      container. scripts/smoke.ps1 defaults to 3000, so point it at the API for
      this loop:
          powershell -ExecutionPolicy Bypass -File scripts/smoke.ps1 -BaseUrl http://127.0.0.1:8080

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts/dev.ps1

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts/dev.ps1 -DbOnly
#>
[CmdletBinding()]
param(
    [switch]$DbOnly,
    [switch]$NoWorker,
    [switch]$NoWeb,
    [switch]$NoApi
)

. "$PSScriptRoot\lib.ps1"

Set-Location $script:JGRepoRoot
Assert-JGCompose
Assert-JGFile -Path $script:JGEnvFile -Hint 'run scripts/setup.ps1 first'

# --- Database -----------------------------------------------------------------
Write-JGInfo 'Starting PostgreSQL (published on 127.0.0.1:5432 for host access)'

# A tiny override written to a temp file rather than into the repository, so the
# dev loop can reach the database without anyone accidentally committing a
# published-database override to docker-compose.override.yml.
$devOverride = Join-Path $script:JGRepoRoot '.dev-compose.tmp.yml'
$overrideText = @'
# Generated by scripts/dev.ps1. Temporary; deleted immediately. Do not commit.
services:
  db:
    ports:
      - "127.0.0.1:5432:5432"
'@
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($devOverride, $overrideText, $utf8NoBom)

try {
    & docker compose -f docker-compose.yml -f $devOverride up -d --wait db
    if ($LASTEXITCODE -ne 0) { throw 'the database did not become healthy. Check: docker compose logs db' }
}
catch {
    Remove-Item -Force -LiteralPath $devOverride -ErrorAction SilentlyContinue
    Stop-JG $_.Exception.Message
}
finally {
    Remove-Item -Force -LiteralPath $devOverride -ErrorAction SilentlyContinue
}
Write-JGOk 'database ready on 127.0.0.1:5432'

if ($DbOnly) {
    Write-Host ''
    Write-Host 'Database only, as requested. It stays up until you run:'
    Write-Host '    docker compose stop db'
    exit 0
}

# --- Host-side environment ----------------------------------------------------
# Compose service names do not resolve on the host; rewrite them.
$databaseUrl = Get-JGEnvValue -Key 'DATABASE_URL'
if ($databaseUrl -match '@db:') { $databaseUrl = $databaseUrl -replace '@db:', '@127.0.0.1:' }
if (-not $databaseUrl) { Stop-JG 'DATABASE_URL is missing from .env' }
$env:DATABASE_URL = $databaseUrl

if (-not $env:WORKER_API_BASE_URL) { $env:WORKER_API_BASE_URL = 'http://127.0.0.1:8080' }
if (-not $env:WORKER_ID)           { $env:WORKER_ID = "dev-worker-$PID" }
if (-not $env:PORT)                { $env:PORT = '8080' }
# Vite's dev server origin, so cookies and origin verification line up.
if ($env:DEV_APP_ORIGIN) { $env:APP_ORIGIN = $env:DEV_APP_ORIGIN } else { $env:APP_ORIGIN = 'http://localhost:5173' }

if (-not $env:FILES_ROOT_DEV) { $env:FILES_ROOT = Join-Path $script:JGRepoRoot '.dev-files' }
else                          { $env:FILES_ROOT = $env:FILES_ROOT_DEV }
New-Item -ItemType Directory -Path $env:FILES_ROOT -Force | Out-Null

# --- Migrations ---------------------------------------------------------------
Write-JGInfo 'Applying migrations...'
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'migrate.ps1') -Local
if ($LASTEXITCODE -ne 0) { Stop-JG 'migrations failed; not starting anything else.' }

# --- Processes ----------------------------------------------------------------
$processes = @()

function Start-JGDevProcess {
    param(
        [Parameter(Mandatory)][string]$Label,
        [Parameter(Mandatory)][string]$FilePath,
        [Parameter(Mandatory)][string[]]$ArgumentList
    )
    Write-JGInfo "starting $Label : $FilePath $($ArgumentList -join ' ')"
    # -NoNewWindow so all output lands in this terminal, as the sh version does.
    $p = Start-Process -FilePath $FilePath -ArgumentList $ArgumentList `
                       -WorkingDirectory $script:JGRepoRoot -NoNewWindow -PassThru
    Write-JGOk "$Label pid $($p.Id)"
    return $p
}

if (-not $NoApi) {
    Assert-JGCommand -Name 'pnpm' -Hint 'Install pnpm: corepack enable; corepack prepare --activate'
    $processes += Start-JGDevProcess -Label 'api' -FilePath 'pnpm' -ArgumentList @('--filter', '@job-getter/api', 'dev')
}
if (-not $NoWeb) {
    Assert-JGCommand -Name 'pnpm' -Hint 'Install pnpm: corepack enable; corepack prepare --activate'
    $processes += Start-JGDevProcess -Label 'web' -FilePath 'pnpm' -ArgumentList @('--filter', '@job-getter/web', 'dev')
}
if (-not $NoWorker) {
    Assert-JGCommand -Name 'uv' -Hint 'Install uv: https://docs.astral.sh/uv/getting-started/installation/'
    # --project so it resolves services/worker/uv.lock regardless of cwd.
    # No --frozen here: a contributor editing pyproject.toml should get a clear
    # resolution error, not a stale environment.
    $processes += Start-JGDevProcess -Label 'worker' -FilePath 'uv' -ArgumentList @('run', '--project', 'services/worker', 'job-getter-worker')
}

Write-Host ''
Write-Host '-----------------------------------------------------------------------'
if (-not $NoWeb)    { Write-Host '  web     http://localhost:5173' }
if (-not $NoApi)    { Write-Host '  api     http://127.0.0.1:8080' }
Write-Host '  db      127.0.0.1:5432'
if (-not $NoWorker) { Write-Host "  worker  $($env:WORKER_ID)" }
Write-Host ''
Write-Host '  Ctrl-C stops the host processes; the database keeps running.'
Write-Host '-----------------------------------------------------------------------'
Write-Host ''

# Wait for any child to exit, then take the rest down rather than leaving a
# half-running stack that looks healthy. Ctrl-C lands in the finally block.
try {
    while ($true) {
        $dead = @($processes | Where-Object { $_.HasExited })
        if ($dead.Count -gt 0) {
            Write-JGWarn "a development process exited (pid $($dead[0].Id)); shutting the rest down"
            break
        }
        Start-Sleep -Milliseconds 500
    }
}
finally {
    Write-Host ''
    Write-JGInfo 'Stopping development processes...'
    foreach ($p in $processes) {
        if (-not $p.HasExited) {
            try { Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue } catch { }
        }
    }
    Write-Host ''
    Write-Host 'Host processes stopped. The database container is still running:'
    Write-Host '    docker compose stop db      # stop it'
    Write-Host '    docker compose down         # stop and remove (data preserved)'
}
